import AnchoredEvolution.Network
import AnchoredEvolution.SemanticComposition

/-!
# Unifying the two tracking formalisms

`Tracking.lean` describes content-sensitive correction through executable
process runs. `Network.lean` describes the same idea as a model-level revision
rule that scales from one model to groups and networks.

This file gives both constructions one common mathematical object: a
**content-indexed transition relation**. The common law is:

* if incoming content is live, at least one transition outcome admits it;
* every transition outcome changes the public record minimally toward that
  content.

The operational process is the nondeterministic instance whose transitions are
post-challenge reachable states. A `Network.Model` is the deterministic instance
whose single outcome is `revise s v`.

The file also separates exact semantic transmission from the weaker relay
condition originally called `Network.Honest`. The latter permits a live
content to be sharpened. Exact boundary faithfulness is the `HFaithful`
condition already used by `SemanticComposition.lean`.
-/

universe u

namespace Anchored.UnifiedTracking

open LearningConstitution Operational Semantic Tracking Network

/-! ## 1. One content-indexed transition law -/

section CommonLaw

variable {State Claim World : Type u}

/-- The common local tracking law for a content-indexed transition relation.
`next v s t` means that `t` is a possible correction outcome from state `s`
when the incoming content is `v`. `record v s` is the public claim exposed at
that state for that content-indexed process. -/
def TransitionTracksAt (meaning : Claim → World → Prop)
    (Candidate : World → Prop)
    (next : Claim → State → State → Prop)
    (record : Claim → State → Claim)
    (s : State) (v : Claim) : Prop :=
  (LiveClaim meaning Candidate v →
      ∃ t, next v s t ∧ Compatible meaning Candidate (record v t) v) ∧
  (∀ t, next v s t →
      MinimalToward meaning Candidate (record v s) (record v t) v)

/-- The same law required at every state and for every incoming content. -/
def TransitionTracking (meaning : Claim → World → Prop)
    (Candidate : World → Prop)
    (next : Claim → State → State → Prop)
    (record : Claim → State → Claim) : Prop :=
  ∀ s v, TransitionTracksAt meaning Candidate next record s v

end CommonLaw

/-! ## 2. The executable-process definition is an instance -/

section OperationalInstance

variable {Agent State Claim Evidence Decision World : Type u}
variable (Pf : Claim → Process Agent State Claim Evidence Decision)
variable (recf : Claim → State → Decision → Claim)

/-- The content-indexed transition relation generated by an actual challenge:
its outcomes are exactly the states reachable after that challenge. -/
def operationalNext (a : Agent) (d : Decision) : Claim → State → State → Prop :=
  fun v s t => AfterChallenge Pf recf v s a d t

/-- The public decision record used by the operational process. -/
def operationalRecord (d : Decision) : Claim → State → Claim :=
  fun v s => recf v s d

variable {Pf recf}

/-- On a live view, the process-level `Tracks` predicate is exactly the common
transition law at that state, participant and decision. The liveness premise is
needed only because the common law deliberately requires admission only for
views that evidence still leaves open. -/
theorem operational_tracks_iff_transition_tracksAt_of_live
    {meaning : Claim → World → Prop} {Candidate : World → Prop}
    {s : State} {a : Agent} {d : Decision} {v : Claim}
    (hlive : LiveClaim meaning Candidate v) :
    Tracks meaning Candidate Pf recf v s a d ↔
      TransitionTracksAt meaning Candidate
        (operationalNext Pf recf a d) (operationalRecord recf d) s v := by
  constructor
  · intro h
    exact ⟨fun _ => h.1, h.2⟩
  · intro h
    exact ⟨h.1 hlive, h.2⟩

end OperationalInstance

/-! ## 3. The scale-free network model is the deterministic instance -/

section ModelInstance

variable {World : Type u}

/-- The deterministic transition relation induced by a `Network.Model`. -/
def modelNext (M : Model World) : Content World → M.State → M.State → Prop :=
  fun v s t => t = M.revise s v

/-- A network model has one public record independent of which content is being
considered; this packages it in the common content-indexed record shape. -/
def modelRecord (M : Model World) : Content World → M.State → Content World :=
  fun _ s => M.record s

/-- **One law, literally.** `Network.Model.Tracking` is equivalent to the
common transition law for the deterministic relation generated by `revise`.
Thus the individual/group/network formalization is not a second tracking
principle; it is a deterministic specialization of the same relation-level
law used by executable processes. -/
theorem model_tracking_iff_transition_tracking (M : Model World)
    (C : Content World) :
    M.Tracking C ↔ TransitionTracking den C (modelNext M) (modelRecord M) := by
  constructor
  · intro h s v
    refine ⟨?_, ?_⟩
    · intro hlive
      exact ⟨M.revise s v, rfl, (h s v).1 hlive⟩
    · intro t ht
      rw [ht]
      exact (h s v).2
  · intro h s v
    have hs := h s v
    refine ⟨?_, ?_⟩
    · intro hlive
      obtain ⟨t, ht, hadm⟩ := hs.1 hlive
      rw [ht] at hadm
      exact hadm
    · exact hs.2 (M.revise s v) rfl

end ModelInstance

/-! ## 4. Exact interfaces versus live-preserving sharpening -/

section Interfaces

variable {World : Type u}

/-- Exact semantic transmission across a channel. This is the same
heterogeneous-faithfulness notion used by `SemanticComposition`, specialized to
content-as-meaning on both sides. -/
def FaithfulChannel (C : Content World) (ch : Channel World) : Prop :=
  SemanticComposition.HFaithful den den C ch

/-- The weaker relay condition from `Network.lean`. It preserves liveness and
never adds worlds relative to the incoming content, but it may sharpen that
content. The old name `Network.Honest` is retained for compatibility. -/
def LiveSharpeningChannel (C : Content World) (ch : Channel World) : Prop :=
  Honest C ch

/-- Exact faithfulness implies the weaker live-preserving sharpening condition. -/
theorem faithful_channel_is_live_sharpening {C : Content World} {ch : Channel World}
    (h : FaithfulChannel C ch) : LiveSharpeningChannel C ch := by
  intro v
  refine ⟨h.1 v, ?_⟩
  rintro ⟨w, hw, hv⟩
  exact ⟨w, hw, h.2 v w hw hv⟩

/-- Exact transmission preserves semantic compatibility in both directions. -/
theorem faithful_channel_compatible_iff {C : Content World} {ch : Channel World}
    (h : FaithfulChannel C ch) (v v' : Content World) :
    Compatible den C (ch v) (ch v') ↔ Compatible den C v v' :=
  SemanticComposition.hfaithful_compatible_iff h v v'

/-- Exact transmission preserves semantic incompatibility in both directions.
In particular, an interface satisfying this stronger condition cannot create
or erase a conflict merely by translating it. -/
theorem faithful_channel_incompatible_iff {C : Content World} {ch : Channel World}
    (h : FaithfulChannel C ch) (v v' : Content World) :
    Incompatible den C (ch v) (ch v') ↔ Incompatible den C v v' :=
  SemanticComposition.hfaithful_incompatible_iff h v v'

/-- A tracking receiver remains tracking behind an exactly faithful channel. -/
theorem via_faithful_tracks {C : Content World} {M : Model World} {ch : Channel World}
    (hM : M.Tracking C) (hch : FaithfulChannel C ch) :
    (M.via ch).Tracking C :=
  via_honest_tracks hM (faithful_channel_is_live_sharpening hch)

end Interfaces

end Anchored.UnifiedTracking
