site_name: Evolution by Emergence
docs_dir: docs      # your Markdown lives here
site_dir: site      # MkDocs will write HTML here

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Front Matter:
      - Preface: Frontmatter/Preface.md
      - Writing Process: Frontmatter/Writing_process.md
      - Introduction: Frontmatter/Introduction.md
      - How to Compile: Frontmatter/Instructions_to_compile_the_book.md
  - Chapters:
      - Chapter 1: Chapters/Chapter_1.md
      # … through Chapter 13
  - Back Matter:
      - Epilogue: Backmatter/Epilogue.md
      - Appendix: Backmatter/Appendix.md
      - Literature: Backmatter/Literature.md
