site_name: Evolution by Emergence
site_url: https://albertjanvanhoek.github.io/Evolution-by-Emergence/
use_directory_urls: true

docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.instant     # live‐update on sidebar clicks
    - navigation.sections    # group headings in sidebar
    - search.highlight       # highlight search terms

# if you want a GitHub link in the header
repo_url: https://github.com/albertjanvanhoek/Evolution-by-Emergence
repo_name: GitHub


# —————————————  HIER BEGINNEN DE MATH‑SECTIES  —————————————
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

  - attr_list

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css
  - styles/figures.css
  - styles/hide-fences.css 

extra_javascript:
  - javascripts/katex.js     # zelf aanmaken in docs/javascripts/
  - https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0/dist/contrib/auto-render.min.js
# ————————————————————————————————————————————————


nav:
  - Front Matter:
      - Index: index.md  
      - Preface: Frontmatter/Preface.md
      - Writing Process: Frontmatter/Writing_process.md

  - Chapters:
      - Chapter 1: Chapters/Chapter_1.md
      - Chapter 2: Chapters/Chapter_2.md
      - Chapter 3: Chapters/Chapter_3.md
      - Chapter 4: Chapters/Chapter_4.md
      - Chapter 5: Chapters/Chapter_5.md
      - Chapter 6: Chapters/Chapter_6.md
      - Chapter 7: Chapters/Chapter_7.md
      - Chapter 8: Chapters/Chapter_8.md
      - Chapter 9: Chapters/Chapter_9.md
      - Chapter 10: Chapters/Chapter_10.md
      - Chapter 11: Chapters/Chapter_11.md
      - Chapter 12: Chapters/Chapter_12.md
      - Chapter 13: Chapters/Chapter_13.md

  - Epilogue & Appendix:
      - Epilogue: Backmatter/Epilogue.md
      - Appendix: Backmatter/Appendix.md
      - Appendix II: Backmatter/AppendixII.md
      - Appendix III: Backmatter/AppendixIII.md
      - Appendix IV: Backmatter/AppendixIV.md
      - Appendix V: Backmatter/AppendixV.md
      - Appendix VI: Backmatter/AppendixVI.md
      - Appendix VII: Backmatter/AppendixVII.md
      - Appendix VIII: Backmatter/AppendixVIII.md
      - Appendix IX: Backmatter/AppendixIX.md
      - Literature: Backmatter/Literature.md
