site_name: Evolution by Emergence
site_description: A Universal Theory of Networks, Life, and Mind

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

# _do not_ point site_dir at docs/, let it default to 'site'
# docs_dir defaults to 'docs'—that’s where your .md files already are

nav:
  - Home: index.md
  - Front Matter:
    - Preface: Frontmatter/Preface.md
    - Writing Process: Frontmatter/Writing_process.md
    - Introduction: Frontmatter/Introduction.md
    - How to Compile: Frontmatter/Instructions_to_compile_the_book.md
  - Chapters:
    - Chapter 1: Chapters/Chapter_1.md
    - Chapter 2: Chapters/Chapter_2.md
    # …through Chapter 13
  - Back Matter:
    - Epilogue: Backmatter/Epilogue.md
    - Appendix: Backmatter/Appendix.md
    - Literature: Backmatter/Literature.md
