import Mathlib

namespace CumulativeAccessibility

variable {α : Type*}

/-- Preservation of declared accessibility over a target family. -/
def PreservesOn
    (targets : Set α) (oldAccess newAccess : α → Prop) : Prop :=
  ∀ x, x ∈ targets → oldAccess x → newAccess x

/-- A strict accessibility click: all previously accessible declared targets
remain accessible and at least one declared target becomes newly accessible. -/
def StrictExpandsOn
    (targets : Set α) (oldAccess newAccess : α → Prop) : Prop :=
  PreservesOn targets oldAccess newAccess ∧
    ∃ x, x ∈ targets ∧ ¬ oldAccess x ∧ newAccess x

/-- The declared accessible set generated by an accessibility predicate. -/
def accessibleSet
    (targets : Set α) (access : α → Prop) : Set α :=
  {x | x ∈ targets ∧ access x}

theorem preservesOn_iff_subset
    (targets : Set α) (oldAccess newAccess : α → Prop) :
    PreservesOn targets oldAccess newAccess
      ↔ accessibleSet targets oldAccess ⊆ accessibleSet targets newAccess := by
  constructor
  · intro h x hx
    exact ⟨hx.1, h x hx.1 hx.2⟩
  · intro h x htarget hold
    exact (h ⟨htarget, hold⟩).2

theorem strictExpandsOn_iff_ssubset
    (targets : Set α) (oldAccess newAccess : α → Prop) :
    StrictExpandsOn targets oldAccess newAccess
      ↔ accessibleSet targets oldAccess ⊂ accessibleSet targets newAccess := by
  constructor
  · rintro ⟨hpres, x, hxT, hxOld, hxNew⟩
    refine Set.ssubset_iff_subset_ne.mpr ?_
    constructor
    · exact (preservesOn_iff_subset targets oldAccess newAccess).mp hpres
    · intro heq
      have hxmemNew : x ∈ accessibleSet targets newAccess := ⟨hxT, hxNew⟩
      have hxmemOld : x ∈ accessibleSet targets oldAccess := by simpa [heq] using hxmemNew
      exact hxOld hxmemOld.2
  · intro h
    have hsub : accessibleSet targets oldAccess ⊆ accessibleSet targets newAccess :=
      Set.ssubset_iff_subset_ne.mp h |>.1
    have hne : accessibleSet targets oldAccess ≠ accessibleSet targets newAccess :=
      Set.ssubset_iff_subset_ne.mp h |>.2
    refine ⟨(preservesOn_iff_subset targets oldAccess newAccess).mpr hsub, ?_⟩
    by_contra hnone
    push_neg at hnone
    apply hne
    ext x
    constructor
    · intro hxOldSet
      exact hsub hxOldSet
    · intro hxNew
      have hOld : oldAccess x := by
        by_contra hxOld
        exact hnone x hxNew.1 hxOld hxNew.2
      exact ⟨hxNew.1, hOld⟩

theorem preservesOn_refl
    (targets : Set α) (access : α → Prop) :
    PreservesOn targets access access := by
  intro x hx h
  exact h

theorem preservesOn_trans
    (targets : Set α) (a b c : α → Prop)
    (hab : PreservesOn targets a b)
    (hbc : PreservesOn targets b c) :
    PreservesOn targets a c := by
  intro x hx ha
  exact hbc x hx (hab x hx ha)

/-- Once a strict click has occurred, any later preservation step retains
strict expansion relative to the earlier baseline. -/
theorem strictExpandsOn_trans_preserves
    (targets : Set α) (a b c : α → Prop)
    (hab : StrictExpandsOn targets a b)
    (hbc : PreservesOn targets b c) :
    StrictExpandsOn targets a c := by
  rcases hab with ⟨habPres, x, hxT, hxNotA, hxB⟩
  refine ⟨preservesOn_trans targets a b c habPres hbc, x, hxT, hxNotA, ?_⟩
  exact hbc x hxT hxB

/-- A later strict click also creates strict expansion relative to any earlier
baseline whose access was preserved into the pre-click state. -/
theorem preserves_trans_strictExpandsOn
    (targets : Set α) (a b c : α → Prop)
    (hab : PreservesOn targets a b)
    (hbc : StrictExpandsOn targets b c) :
    StrictExpandsOn targets a c := by
  rcases hbc with ⟨hbcPres, x, hxT, hxNotB, hxC⟩
  refine ⟨preservesOn_trans targets a b c hab hbcPres, x, hxT, ?_, hxC⟩
  intro hxA
  exact hxNotB (hab x hxT hxA)

theorem strictExpandsOn_trans
    (targets : Set α) (a b c : α → Prop)
    (hab : StrictExpandsOn targets a b)
    (hbc : StrictExpandsOn targets b c) :
    StrictExpandsOn targets a c := by
  exact strictExpandsOn_trans_preserves targets a b c hab hbc.1

/-- Thresholded accessibility from a scalar score, e.g. a finite-horizon
hitting probability. Higher score means more accessible. -/
def AccessibleByScore
    (score : α → ℝ) (threshold : ℝ) : α → Prop :=
  fun x => threshold ≤ score x

/-- Pointwise score improvement over a declared target family. -/
def ScoreDominatesOn
    (targets : Set α) (oldScore newScore : α → ℝ) : Prop :=
  ∀ x, x ∈ targets → oldScore x ≤ newScore x

theorem scoreDominates_preservesOn
    (targets : Set α)
    (oldScore newScore : α → ℝ) (threshold : ℝ)
    (hdom : ScoreDominatesOn targets oldScore newScore) :
    PreservesOn targets
      (AccessibleByScore oldScore threshold)
      (AccessibleByScore newScore threshold) := by
  intro x hx hOld
  exact le_trans hOld (hdom x hx)

theorem strictExpandsOn_of_score_crossing
    (targets : Set α)
    (oldScore newScore : α → ℝ) (threshold : ℝ)
    (hdom : ScoreDominatesOn targets oldScore newScore)
    (x : α) (hxT : x ∈ targets)
    (hOld : oldScore x < threshold)
    (hNew : threshold ≤ newScore x) :
    StrictExpandsOn targets
      (AccessibleByScore oldScore threshold)
      (AccessibleByScore newScore threshold) := by
  refine ⟨scoreDominates_preservesOn targets oldScore newScore threshold hdom,
    x, hxT, ?_, hNew⟩
  intro h
  exact (not_le_of_gt hOld) h

/-- Budget-feasible realization under a scalar difficulty or cost.
Lower cost means more accessible. This is a mechanism-level specialization,
not a replacement for the paper's probabilistic accessibility kernel. -/
def AccessibleByCost
    (cost : α → ℝ) (budget : ℝ) : α → Prop :=
  fun x => cost x ≤ budget

/-- Pointwise non-increase of cost over a declared target family. -/
def CostDominatesOn
    (targets : Set α) (oldCost newCost : α → ℝ) : Prop :=
  ∀ x, x ∈ targets → newCost x ≤ oldCost x

theorem costDominates_preservesOn
    (targets : Set α)
    (oldCost newCost : α → ℝ) (budget : ℝ)
    (hdom : CostDominatesOn targets oldCost newCost) :
    PreservesOn targets
      (AccessibleByCost oldCost budget)
      (AccessibleByCost newCost budget) := by
  intro x hx hOld
  exact le_trans (hdom x hx) hOld

theorem strictExpandsOn_of_cost_crossing
    (targets : Set α)
    (oldCost newCost : α → ℝ) (budget : ℝ)
    (hdom : CostDominatesOn targets oldCost newCost)
    (x : α) (hxT : x ∈ targets)
    (hOld : budget < oldCost x)
    (hNew : newCost x ≤ budget) :
    StrictExpandsOn targets
      (AccessibleByCost oldCost budget)
      (AccessibleByCost newCost budget) := by
  refine ⟨costDominates_preservesOn targets oldCost newCost budget hdom,
    x, hxT, ?_, hNew⟩
  intro h
  exact (not_le_of_gt hOld) h

/-- A target is route-feasible within budget when at least one admissible
route realizes it at or below the declared budget. -/
def ReachableWithinBudget {ρ : Type*}
    (routes : α → ρ → Prop) (cost : α → ρ → ℝ)
    (budget : ℝ) : α → Prop :=
  fun x => ∃ r, routes x r ∧ cost x r ≤ budget

/-- Route-level dominance: every old route to a declared target has some
later admissible route that is no more costly. The later route need not be
materially identical to the old route. -/
def RouteDominatesOn {ρ : Type*}
    (targets : Set α)
    (oldRoutes newRoutes : α → ρ → Prop)
    (oldCost newCost : α → ρ → ℝ) : Prop :=
  ∀ x, x ∈ targets → ∀ r, oldRoutes x r →
    ∃ r', newRoutes x r' ∧ newCost x r' ≤ oldCost x r

theorem routeDominatesOn_refl {ρ : Type*}
    (targets : Set α)
    (routes : α → ρ → Prop)
    (cost : α → ρ → ℝ) :
    RouteDominatesOn targets routes routes cost cost := by
  intro x hx r hr
  exact ⟨r, hr, le_rfl⟩

/-- Non-destructive route extension composes: if every old route has a
no-more-costly middle realization, and every such middle route has a
no-more-costly later realization, then every old route has a no-more-costly
later realization. -/
theorem routeDominatesOn_trans {ρ : Type*}
    (targets : Set α)
    (routes0 routes1 routes2 : α → ρ → Prop)
    (cost0 cost1 cost2 : α → ρ → ℝ)
    (h01 : RouteDominatesOn targets routes0 routes1 cost0 cost1)
    (h12 : RouteDominatesOn targets routes1 routes2 cost1 cost2) :
    RouteDominatesOn targets routes0 routes2 cost0 cost2 := by
  intro x hx r0 hr0
  rcases h01 x hx r0 hr0 with ⟨r1, hr1, hc10⟩
  rcases h12 x hx r1 hr1 with ⟨r2, hr2, hc21⟩
  exact ⟨r2, hr2, le_trans hc21 hc10⟩

/-- Route-level non-destructive extension preserves every declared target
that was feasible within the same budget. -/
theorem routeDominates_preservesOn {ρ : Type*}
    (targets : Set α)
    (oldRoutes newRoutes : α → ρ → Prop)
    (oldCost newCost : α → ρ → ℝ)
    (budget : ℝ)
    (hdom : RouteDominatesOn targets oldRoutes newRoutes oldCost newCost) :
    PreservesOn targets
      (ReachableWithinBudget oldRoutes oldCost budget)
      (ReachableWithinBudget newRoutes newCost budget) := by
  intro x hx hOld
  rcases hOld with ⟨r, hr, hcost⟩
  rcases hdom x hx r hr with ⟨r', hr', hle⟩
  exact ⟨r', hr', le_trans hle hcost⟩

/-- If route dominance preserves all old budget-feasible targets and some
declared target gains a newly feasible route, the route extension is a strict
accessibility click at that budget. -/
theorem strictExpandsOn_of_new_route {ρ : Type*}
    (targets : Set α)
    (oldRoutes newRoutes : α → ρ → Prop)
    (oldCost newCost : α → ρ → ℝ)
    (budget : ℝ)
    (hdom : RouteDominatesOn targets oldRoutes newRoutes oldCost newCost)
    (x : α) (hxT : x ∈ targets)
    (hOld : ¬ ReachableWithinBudget oldRoutes oldCost budget x)
    (rNew : ρ)
    (hrNew : newRoutes x rNew)
    (hcostNew : newCost x rNew ≤ budget) :
    StrictExpandsOn targets
      (ReachableWithinBudget oldRoutes oldCost budget)
      (ReachableWithinBudget newRoutes newCost budget) := by
  refine ⟨routeDominates_preservesOn targets oldRoutes newRoutes
    oldCost newCost budget hdom, x, hxT, hOld, ?_⟩
  exact ⟨rNew, hrNew, hcostNew⟩

/-- Loss of any previously accessible declared target rules out preservation
and therefore rules out a strict monotone ratchet click. -/
theorem not_preservesOn_of_lost_target
    (targets : Set α) (oldAccess newAccess : α → Prop)
    (x : α) (hxT : x ∈ targets)
    (hOld : oldAccess x) (hNew : ¬ newAccess x) :
    ¬ PreservesOn targets oldAccess newAccess := by
  intro h
  exact hNew (h x hxT hOld)

#print axioms preservesOn_iff_subset
#print axioms strictExpandsOn_iff_ssubset
#print axioms preservesOn_refl
#print axioms preservesOn_trans
#print axioms strictExpandsOn_trans_preserves
#print axioms preserves_trans_strictExpandsOn
#print axioms strictExpandsOn_trans
#print axioms scoreDominates_preservesOn
#print axioms strictExpandsOn_of_score_crossing
#print axioms costDominates_preservesOn
#print axioms strictExpandsOn_of_cost_crossing
#print axioms routeDominatesOn_refl
#print axioms routeDominatesOn_trans
#print axioms routeDominates_preservesOn
#print axioms strictExpandsOn_of_new_route
#print axioms not_preservesOn_of_lost_target

end CumulativeAccessibility
