import Mathlib

namespace CumulativeAccessibility

variable {α : Type*}

/-- Preservation of declared accessibility over a target family. -/
def PreservesOn
    (targets : Set α) (oldAccess newAccess : α → Prop) : Prop :=
  ∀ x, x ∈ targets → oldAccess x → newAccess x

/-- A strict accessibility click: all previously accessible declared targets
remain accessible and at least one declared target becomes newly accessible. -/
def StrictExpandsOn
    (targets : Set α) (oldAccess newAccess : α → Prop) : Prop :=
  PreservesOn targets oldAccess newAccess ∧
    ∃ x, x ∈ targets ∧ ¬ oldAccess x ∧ newAccess x

/-- The declared accessible set generated by an accessibility predicate. -/
def accessibleSet
    (targets : Set α) (access : α → Prop) : Set α :=
  {x | x ∈ targets ∧ access x}

theorem preservesOn_iff_subset
    (targets : Set α) (oldAccess newAccess : α → Prop) :
    PreservesOn targets oldAccess newAccess
      ↔ accessibleSet targets oldAccess ⊆ accessibleSet targets newAccess := by
  constructor
  · intro h x hx
    exact ⟨hx.1, h x hx.1 hx.2⟩
  · intro h x htarget hold
    exact (h ⟨htarget, hold⟩).2

theorem strictExpandsOn_iff_ssubset
    (targets : Set α) (oldAccess newAccess : α → Prop) :
    StrictExpandsOn targets oldAccess newAccess
      ↔ accessibleSet targets oldAccess ⊂ accessibleSet targets newAccess := by
  constructor
  · rintro ⟨hpres, x, hxT, hxOld, hxNew⟩
    refine Set.ssubset_iff_subset_ne.mpr ?_
    constructor
    · exact (preservesOn_iff_subset targets oldAccess newAccess).mp hpres
    · intro heq
      have hxmemNew : x ∈ accessibleSet targets newAccess := ⟨hxT, hxNew⟩
      have hxmemOld : x ∈ accessibleSet targets oldAccess := by simpa [heq] using hxmemNew
      exact hxOld hxmemOld.2
  · intro h
    have hsub : accessibleSet targets oldAccess ⊆ accessibleSet targets newAccess :=
      Set.ssubset_iff_subset_ne.mp h |>.1
    have hne : accessibleSet targets oldAccess ≠ accessibleSet targets newAccess :=
      Set.ssubset_iff_subset_ne.mp h |>.2
    refine ⟨(preservesOn_iff_subset targets oldAccess newAccess).mpr hsub, ?_⟩
    by_contra hnone
    push_neg at hnone
    apply hne
    ext x
    constructor
    · intro hxOldSet
      exact hsub hxOldSet
    · intro hxNew
      have hOld : oldAccess x := by
        by_contra hxOld
        exact hnone x hxNew.1 hxOld hxNew.2
      exact ⟨hxNew.1, hOld⟩

theorem preservesOn_refl
    (targets : Set α) (access : α → Prop) :
    PreservesOn targets access access := by
  intro x hx h
  exact h

theorem preservesOn_trans
    (targets : Set α) (a b c : α → Prop)
    (hab : PreservesOn targets a b)
    (hbc : PreservesOn targets b c) :
    PreservesOn targets a c := by
  intro x hx ha
  exact hbc x hx (hab x hx ha)

/-- Once a strict click has occurred, any later preservation step retains
strict expansion relative to the earlier baseline. -/
theorem strictExpandsOn_trans_preserves
    (targets : Set α) (a b c : α → Prop)
    (hab : StrictExpandsOn targets a b)
    (hbc : PreservesOn targets b c) :
    StrictExpandsOn targets a c := by
  rcases hab with ⟨habPres, x, hxT, hxNotA, hxB⟩
  refine ⟨preservesOn_trans targets a b c habPres hbc, x, hxT, hxNotA, ?_⟩
  exact hbc x hxT hxB

/-- A later strict click also creates strict expansion relative to any earlier
baseline whose access was preserved into the pre-click state. -/
theorem preserves_trans_strictExpandsOn
    (targets : Set α) (a b c : α → Prop)
    (hab : PreservesOn targets a b)
    (hbc : StrictExpandsOn targets b c) :
    StrictExpandsOn targets a c := by
  rcases hbc with ⟨hbcPres, x, hxT, hxNotB, hxC⟩
  refine ⟨preservesOn_trans targets a b c hab hbcPres, x, hxT, ?_, hxC⟩
  intro hxA
  exact hxNotB (hab x hxT hxA)

theorem strictExpandsOn_trans
    (targets : Set α) (a b c : α → Prop)
    (hab : StrictExpandsOn targets a b)
    (hbc : StrictExpandsOn targets b c) :
    StrictExpandsOn targets a c := by
  exact strictExpandsOn_trans_preserves targets a b c hab hbc.1

/-- Thresholded accessibility from a scalar score, e.g. a finite-horizon
hitting probability. Higher score means more accessible. -/
def AccessibleByScore
    (score : α → ℝ) (threshold : ℝ) : α → Prop :=
  fun x => threshold ≤ score x

/-- Pointwise score improvement over a declared target family. -/
def ScoreDominatesOn
    (targets : Set α) (oldScore newScore : α → ℝ) : Prop :=
  ∀ x, x ∈ targets → oldScore x ≤ newScore x

theorem scoreDominates_preservesOn
    (targets : Set α)
    (oldScore newScore : α → ℝ) (threshold : ℝ)
    (hdom : ScoreDominatesOn targets oldScore newScore) :
    PreservesOn targets
      (AccessibleByScore oldScore threshold)
      (AccessibleByScore newScore threshold) := by
  intro x hx hOld
  exact le_trans hOld (hdom x hx)

theorem strictExpandsOn_of_score_crossing
    (targets : Set α)
    (oldScore newScore : α → ℝ) (threshold : ℝ)
    (hdom : ScoreDominatesOn targets oldScore newScore)
    (x : α) (hxT : x ∈ targets)
    (hOld : oldScore x < threshold)
    (hNew : threshold ≤ newScore x) :
    StrictExpandsOn targets
      (AccessibleByScore oldScore threshold)
      (AccessibleByScore newScore threshold) := by
  refine ⟨scoreDominates_preservesOn targets oldScore newScore threshold hdom,
    x, hxT, ?_, hNew⟩
  intro h
  exact (not_le_of_gt hOld) h

/-- Budget-feasible realization under a scalar difficulty or cost.
Lower cost means more accessible. This is a mechanism-level specialization,
not a replacement for the paper's probabilistic accessibility kernel. -/
def AccessibleByCost
    (cost : α → ℝ) (budget : ℝ) : α → Prop :=
  fun x => cost x ≤ budget

/-- Pointwise non-increase of cost over a declared target family. -/
def CostDominatesOn
    (targets : Set α) (oldCost newCost : α → ℝ) : Prop :=
  ∀ x, x ∈ targets → newCost x ≤ oldCost x

theorem costDominates_preservesOn
    (targets : Set α)
    (oldCost newCost : α → ℝ) (budget : ℝ)
    (hdom : CostDominatesOn targets oldCost newCost) :
    PreservesOn targets
      (AccessibleByCost oldCost budget)
      (AccessibleByCost newCost budget) := by
  intro x hx hOld
  exact le_trans (hdom x hx) hOld

theorem strictExpandsOn_of_cost_crossing
    (targets : Set α)
    (oldCost newCost : α → ℝ) (budget : ℝ)
    (hdom : CostDominatesOn targets oldCost newCost)
    (x : α) (hxT : x ∈ targets)
    (hOld : budget < oldCost x)
    (hNew : newCost x ≤ budget) :
    StrictExpandsOn targets
      (AccessibleByCost oldCost budget)
      (AccessibleByCost newCost budget) := by
  refine ⟨costDominates_preservesOn targets oldCost newCost budget hdom,
    x, hxT, ?_, hNew⟩
  intro h
  exact (not_le_of_gt hOld) h

/-! ## Shared-budget specialization: retention, slack, and two-click existence -/

/-- A scalar cost profile over capabilities. -/
abbrev Cost (α : Type*) := α → ℝ

/-- Retention of a declared target family under a common scalar budget. -/
def RetainsCostOn
    (targets : Set α) (oldCost newCost : Cost α) (budget : ℝ) : Prop :=
  PreservesOn targets
    (AccessibleByCost oldCost budget)
    (AccessibleByCost newCost budget)

/-- Pointwise cost domination is achievable in general; it is not a vacuous
order. This abstract witness prevents the uniform-dilution impossibility below
from being misread as an impossibility theorem for all acquisitions. -/
theorem exists_strictCostDominatingStep :
    ∃ oldCost newCost : Cost (Fin 2),
      CostDominatesOn Set.univ oldCost newCost ∧
      ∀ x, newCost x < oldCost x := by
  refine ⟨fun _ => (1 : ℝ), fun _ => (0 : ℝ), ?_, ?_⟩
  · intro x hx
    norm_num
  · intro x
    norm_num

/-- Uniform positive dilution cannot pointwise dominate a positive inherited
cost on a declared target. This is a statement about the dilutive topology,
not about acquisitions in general. -/
theorem not_costDominates_scaled
    (targets : Set α) (cost : Cost α)
    {kappa : ℝ} (hkappa : 0 < kappa)
    (x0 : α) (hx0 : x0 ∈ targets) (hpos : 0 < cost x0) :
    ¬ CostDominatesOn targets cost (fun x => (1 + kappa) * cost x) := by
  intro h
  have hx := h x0 hx0
  nlinarith

/-- Slack relative to a positive binding cost: the proportional extra load
that can be absorbed before the binding capability crosses the budget. -/
noncomputable def Margin (budget bindingCost : ℝ) : ℝ :=
  budget / bindingCost - 1

theorem margin_nonneg
    {budget bindingCost : ℝ}
    (hcost : 0 < bindingCost)
    (hinside : bindingCost ≤ budget) :
    0 ≤ Margin budget bindingCost := by
  unfold Margin
  rw [sub_nonneg]
  exact (le_div_iff₀ hcost).2 (by simpa using hinside)

/-- Winding/spending identity. Positive budget is required because otherwise
the normalized slack ratio is degenerate. -/
theorem margin_ratio
    {budget oldBinding newBinding : ℝ}
    (hbudget : 0 < budget)
    (hold : 0 < oldBinding)
    (hnew : 0 < newBinding) :
    (1 + Margin budget newBinding) /
        (1 + Margin budget oldBinding)
      =
    oldBinding / newBinding := by
  unfold Margin
  field_simp [ne_of_gt hbudget, ne_of_gt hold, ne_of_gt hnew]
  ring

/-- General winding/spending update when the binding cost changes by a
positive multiplicative factor r. -/
theorem margin_update
    {budget oldBinding r : ℝ}
    (hold : 0 < oldBinding)
    (hr : 0 < r) :
    1 + Margin budget (r * oldBinding)
      =
    (1 + Margin budget oldBinding) / r := by
  unfold Margin
  field_simp [ne_of_gt hold, ne_of_gt hr]
  ring

/-- For positive budget and binding cost, multiplying the binding cost by r
winds the margin exactly when r < 1. -/
theorem winds_iff_binding_cost_falls
    {budget oldBinding r : ℝ}
    (hbudget : 0 < budget)
    (hold : 0 < oldBinding)
    (hr : 0 < r) :
    Margin budget oldBinding < Margin budget (r * oldBinding)
      ↔
    r < 1 := by
  unfold Margin
  rw [sub_lt_sub_iff_right]
  have hrOld : 0 < r * oldBinding := mul_pos hr hold
  rw [div_lt_div_iff_of_pos_left hbudget hold hrOld]
  simpa only [one_mul] using
    (mul_lt_mul_right hold : r * oldBinding < 1 * oldBinding ↔ r < 1)

/-- If a currently positive margin accepts a load equal to a strict fraction
u of that margin, with 0 <= u < 1, the updated margin remains strictly
positive. This is the deterministic core of the finite-step correction:
arbitrarily small accepted loads need not exhaust margin in finitely many
clicks. -/
theorem accepted_fraction_margin_positive
    {M u : ℝ}
    (hM : 0 < M)
    (hu0 : 0 ≤ u)
    (hu1 : u < 1) :
    0 < M * (1 - u) / (1 + u * M) := by
  have hnum : 0 < M * (1 - u) := mul_pos hM (by linarith)
  have hden : 0 < 1 + u * M := by
    have hprod : 0 ≤ u * M := mul_nonneg hu0 (le_of_lt hM)
    linarith
  exact div_pos hnum hden

/-- Exact margin recursion for a uniformly dilutive load.
This identity alone does not imply finite-step exhaustion when accepted loads
may become arbitrarily small. -/
theorem margin_dilute
    {budget oldBinding kappa : ℝ}
    (hold : 0 < oldBinding)
    (hkappa : -1 < kappa) :
    Margin budget ((1 + kappa) * oldBinding)
      =
    (Margin budget oldBinding - kappa) / (1 + kappa) := by
  unfold Margin
  have h1 : (1 : ℝ) + kappa ≠ 0 := by linarith
  field_simp [ne_of_gt hold, h1]
  ring

/-- Exact declared-set budget bound under uniform dilution.
bindingCost is the attained maximum cost among the declared capabilities
that are already within budget. -/
theorem retainsCostOn_scaled_iff_margin
    (targets : Set α) (cost : Cost α)
    {budget kappa bindingCost : ℝ}
    (hkappa : 0 ≤ kappa)
    (hbinding : 0 < bindingCost)
    (hub : ∀ x, x ∈ targets → cost x ≤ budget → cost x ≤ bindingCost)
    (x0 : α) (hx0 : x0 ∈ targets)
    (hattain : cost x0 = bindingCost)
    (hinside : bindingCost ≤ budget) :
    RetainsCostOn targets cost (fun x => (1 + kappa) * cost x) budget
      ↔
    kappa ≤ Margin budget bindingCost := by
  constructor
  · intro h
    have hxold : AccessibleByCost cost budget x0 := by
      unfold AccessibleByCost
      simpa [hattain] using hinside
    have hxnew := h x0 hx0 hxold
    unfold AccessibleByCost at hxnew
    simp [hattain] at hxnew
    have hdiv : (1 : ℝ) + kappa ≤ budget / bindingCost :=
      (le_div_iff₀ hbinding).2 hxnew
    unfold Margin
    linarith
  · intro hk x hxT hxold
    unfold AccessibleByCost at hxold ⊢
    have h1 : (1 : ℝ) + kappa ≤ budget / bindingCost := by
      unfold Margin at hk
      linarith
    have hbound : (1 + kappa) * bindingCost ≤ budget :=
      (le_div_iff₀ hbinding).1 h1
    have hscale : 0 ≤ (1 : ℝ) + kappa := by linarith
    have hxbind : cost x ≤ bindingCost := hub x hxT hxold
    have hmul :
        (1 + kappa) * cost x ≤ (1 + kappa) * bindingCost :=
      mul_le_mul_of_nonneg_left hxbind hscale
    linarith

/-- A winding step opens a nonempty interval of future dilutive couplings:
loads in this interval were too large for the earlier margin but fit inside
the later one. -/
theorem margin_increase_opens_coupling_window
    {M0 M1 : ℝ} (hM0 : 0 ≤ M0) (hinc : M0 < M1) :
    ∃ kappa, 0 ≤ kappa ∧ M0 < kappa ∧ kappa ≤ M1 := by
  refine ⟨(M0 + M1) / 2, ?_, ?_, ?_⟩ <;> linarith

/-- A coupling lying above the old margin but at or below the new margin
switches the same uniformly dilutive acquisition from unaffordable to
affordable, provided each margin is computed from an attained declared-set
binding cost. -/
theorem coupling_between_margins_switches_retention
    (targets : Set α)
    (oldCost newCost : Cost α)
    {budget kappa oldBinding newBinding : ℝ}
    (hkappa : 0 ≤ kappa)
    (hOldBinding : 0 < oldBinding)
    (hNewBinding : 0 < newBinding)
    (hOldHub :
      ∀ x, x ∈ targets → oldCost x ≤ budget → oldCost x ≤ oldBinding)
    (hNewHub :
      ∀ x, x ∈ targets → newCost x ≤ budget → newCost x ≤ newBinding)
    (oldWitness newWitness : α)
    (hOldWitnessT : oldWitness ∈ targets)
    (hNewWitnessT : newWitness ∈ targets)
    (hOldAttain : oldCost oldWitness = oldBinding)
    (hNewAttain : newCost newWitness = newBinding)
    (hOldInside : oldBinding ≤ budget)
    (hNewInside : newBinding ≤ budget)
    (hTooLargeBefore : Margin budget oldBinding < kappa)
    (hFitsAfter : kappa ≤ Margin budget newBinding) :
    ¬ RetainsCostOn targets oldCost
        (fun x => (1 + kappa) * oldCost x) budget
      ∧
    RetainsCostOn targets newCost
        (fun x => (1 + kappa) * newCost x) budget := by
  constructor
  · intro hret
    have hk :=
      (retainsCostOn_scaled_iff_margin
        targets oldCost hkappa hOldBinding hOldHub
        oldWitness hOldWitnessT hOldAttain hOldInside).mp hret
    linarith
  · exact
      (retainsCostOn_scaled_iff_margin
        targets newCost hkappa hNewBinding hNewHub
        newWitness hNewWitnessT hNewAttain hNewInside).2 hFitsAfter

/-- If maintained production rises, then for every positive coupling there is
a nonempty interval of module thresholds that are unattainable before and
attainable after. -/
theorem production_increase_opens_threshold_window
    {X0 X1 kappa : ℝ}
    (hX : X0 < X1) (hkappa : 0 < kappa) :
    ∃ theta,
      X0 * kappa / (1 + kappa) < theta ∧
      theta ≤ X1 * kappa / (1 + kappa) := by
  have hden : 0 < (1 : ℝ) + kappa := by linarith
  have hnum : X0 * kappa < X1 * kappa :=
    mul_lt_mul_of_pos_right hX hkappa
  have hlr :
      X0 * kappa / (1 + kappa) <
      X1 * kappa / (1 + kappa) :=
    (div_lt_div_iff_of_pos_right hden).2 hnum
  refine ⟨
    (X0 * kappa / (1 + kappa) + X1 * kappa / (1 + kappa)) / 2,
    ?_, ?_⟩ <;> linarith

/-- Four capabilities used for an exact two-click witness. -/
inductive Cap4
  | A | B | C | D
  deriving DecidableEq

open Cap4

/-- Baseline exact costs for the rational witness. -/
noncomputable def twoClickCost0 : Cost Cap4
  | A => 3 / 5
  | B => 3 / 10
  | C => 2
  | D => 2

/-- After a productive click with exact closed-form parameters
lambda=6/5, f=11/25, v=2. -/
noncomputable def twoClickCost1 : Cost Cap4
  | A => 33 / 70
  | B => 99 / 196
  | C => 3 / 7
  | D => 2

/-- After adding a non-returning downstream module with kappa=9/10. -/
noncomputable def twoClickCost2 : Cost Cap4
  | A => 627 / 700
  | B => 1881 / 1960
  | C => 57 / 70
  | D => 19 / 21

/-- Counterfactual cost profile for trying the second click directly from the
baseline. -/
noncomputable def directSecondClickCost : Cost Cap4
  | A => 57 / 50
  | B => 57 / 100
  | C => 2
  | D => 19 / 18

/-- Exact rational positive existence witness:
{A,B} -> {A,B,C} -> {A,B,C,D} at budget 1. -/
theorem exact_two_click_witness :
    StrictExpandsOn Set.univ
      (AccessibleByCost twoClickCost0 1)
      (AccessibleByCost twoClickCost1 1)
    ∧
    StrictExpandsOn Set.univ
      (AccessibleByCost twoClickCost1 1)
      (AccessibleByCost twoClickCost2 1) := by
  constructor
  · refine ⟨?_, C, by simp, ?_, ?_⟩
    · intro x hxT hxOld
      cases x with
      | A => norm_num [AccessibleByCost, twoClickCost0, twoClickCost1]
      | B => norm_num [AccessibleByCost, twoClickCost0, twoClickCost1]
      | C => norm_num [AccessibleByCost, twoClickCost0] at hxOld
      | D => norm_num [AccessibleByCost, twoClickCost0] at hxOld
    · norm_num [AccessibleByCost, twoClickCost0]
    · norm_num [AccessibleByCost, twoClickCost1]
  · refine ⟨?_, D, by simp, ?_, ?_⟩
    · intro x hxT hxOld
      cases x with
      | A => norm_num [AccessibleByCost, twoClickCost1, twoClickCost2]
      | B => norm_num [AccessibleByCost, twoClickCost1, twoClickCost2]
      | C => norm_num [AccessibleByCost, twoClickCost1, twoClickCost2]
      | D => norm_num [AccessibleByCost, twoClickCost1] at hxOld
    · norm_num [AccessibleByCost, twoClickCost1]
    · norm_num [AccessibleByCost, twoClickCost2]

/-- The second click is unavailable at the baseline: it loses inherited A,
and D itself remains outside the budget. -/
theorem exact_second_click_unavailable_at_baseline :
    ¬ PreservesOn Set.univ
        (AccessibleByCost twoClickCost0 1)
        (AccessibleByCost directSecondClickCost 1)
    ∧
    ¬ AccessibleByCost directSecondClickCost 1 D := by
  constructor
  · intro h
    have hAold : AccessibleByCost twoClickCost0 1 A := by
      norm_num [AccessibleByCost, twoClickCost0]
    have hAnew := h A (by simp) hAold
    norm_num [AccessibleByCost, directSecondClickCost] at hAnew
  · norm_num [AccessibleByCost, directSecondClickCost]

/-- The exact rational productive first click winds the declared {A,B,C}
repertoire: its margin rises from 2/3 to 97/99. -/
theorem exact_first_click_winds :
    Margin 1 (3 / 5) < Margin 1 (99 / 196) := by
  norm_num [Margin]

/-- kappa=9/10 lies in the coupling interval opened by the exact first click. -/
theorem exact_second_coupling_in_opened_window :
    Margin 1 (3 / 5) < (9 / 10 : ℝ)
      ∧
    (9 / 10 : ℝ) ≤ Margin 1 (99 / 196) := by
  norm_num [Margin]

/-- theta_D=1/2 lies in the exact production window opened by
X0=1 -> X1=7/6 at kappa=9/10. -/
theorem exact_second_threshold_in_opened_window :
    (1 : ℝ) * (9 / 10) / (1 + 9 / 10) < 1 / 2
      ∧
    (1 / 2 : ℝ) ≤
      (7 / 6) * (9 / 10) / (1 + 9 / 10) := by
  norm_num

/-- A concrete strict pointwise cost improvement, showing again that cost
domination is possible outside the dilutive topology. These exact rational
values come from the non-substituting productive extension with f=1/100,
v=125 and lambda=3/2 in the same closed-form production-network family.
The equilibrium-formula arithmetic is checked here; the ODE/eigenvalue
derivation itself remains inherited from the parent model. -/
theorem exact_productive_extension_strictly_dominates :
    let oldCost : Cost (Fin 2) := ![(3 : ℝ) / 5, 3 / 10]
    let newCost : Cost (Fin 2) := ![(753 : ℝ) / 2000, 2259 / 8000]
    CostDominatesOn Set.univ oldCost newCost ∧
      ∀ x, newCost x < oldCost x := by
  dsimp
  constructor
  · intro x hx
    fin_cases x <;> norm_num
  · intro x
    fin_cases x <;> norm_num

/-- The same rational productive witness winds the binding-cost margin from
2/3 to 1247/753. -/
theorem exact_productive_extension_winds_margin :
    Margin 1 ((753 : ℝ) / 2000) = 1247 / 753
      ∧
    Margin 1 ((3 : ℝ) / 5) < Margin 1 (753 / 2000) := by
  constructor <;> norm_num [Margin]

/-- A target is route-feasible within budget when at least one admissible
route realizes it at or below the declared budget. -/
def ReachableWithinBudget {ρ : Type*}
    (routes : α → ρ → Prop) (cost : α → ρ → ℝ)
    (budget : ℝ) : α → Prop :=
  fun x => ∃ r, routes x r ∧ cost x r ≤ budget

/-- Route-level dominance: every old route to a declared target has some
later admissible route that is no more costly. The later route need not be
materially identical to the old route. -/
def RouteDominatesOn {ρ : Type*}
    (targets : Set α)
    (oldRoutes newRoutes : α → ρ → Prop)
    (oldCost newCost : α → ρ → ℝ) : Prop :=
  ∀ x, x ∈ targets → ∀ r, oldRoutes x r →
    ∃ r', newRoutes x r' ∧ newCost x r' ≤ oldCost x r

theorem routeDominatesOn_refl {ρ : Type*}
    (targets : Set α)
    (routes : α → ρ → Prop)
    (cost : α → ρ → ℝ) :
    RouteDominatesOn targets routes routes cost cost := by
  intro x hx r hr
  exact ⟨r, hr, le_rfl⟩

/-- Non-destructive route extension composes: if every old route has a
no-more-costly middle realization, and every such middle route has a
no-more-costly later realization, then every old route has a no-more-costly
later realization. -/
theorem routeDominatesOn_trans {ρ : Type*}
    (targets : Set α)
    (routes0 routes1 routes2 : α → ρ → Prop)
    (cost0 cost1 cost2 : α → ρ → ℝ)
    (h01 : RouteDominatesOn targets routes0 routes1 cost0 cost1)
    (h12 : RouteDominatesOn targets routes1 routes2 cost1 cost2) :
    RouteDominatesOn targets routes0 routes2 cost0 cost2 := by
  intro x hx r0 hr0
  rcases h01 x hx r0 hr0 with ⟨r1, hr1, hc10⟩
  rcases h12 x hx r1 hr1 with ⟨r2, hr2, hc21⟩
  exact ⟨r2, hr2, le_trans hc21 hc10⟩

/-- Route-level non-destructive extension preserves every declared target
that was feasible within the same budget. -/
theorem routeDominates_preservesOn {ρ : Type*}
    (targets : Set α)
    (oldRoutes newRoutes : α → ρ → Prop)
    (oldCost newCost : α → ρ → ℝ)
    (budget : ℝ)
    (hdom : RouteDominatesOn targets oldRoutes newRoutes oldCost newCost) :
    PreservesOn targets
      (ReachableWithinBudget oldRoutes oldCost budget)
      (ReachableWithinBudget newRoutes newCost budget) := by
  intro x hx hOld
  rcases hOld with ⟨r, hr, hcost⟩
  rcases hdom x hx r hr with ⟨r', hr', hle⟩
  exact ⟨r', hr', le_trans hle hcost⟩

/-- If route dominance preserves all old budget-feasible targets and some
declared target gains a newly feasible route, the route extension is a strict
accessibility click at that budget. -/
theorem strictExpandsOn_of_new_route {ρ : Type*}
    (targets : Set α)
    (oldRoutes newRoutes : α → ρ → Prop)
    (oldCost newCost : α → ρ → ℝ)
    (budget : ℝ)
    (hdom : RouteDominatesOn targets oldRoutes newRoutes oldCost newCost)
    (x : α) (hxT : x ∈ targets)
    (hOld : ¬ ReachableWithinBudget oldRoutes oldCost budget x)
    (rNew : ρ)
    (hrNew : newRoutes x rNew)
    (hcostNew : newCost x rNew ≤ budget) :
    StrictExpandsOn targets
      (ReachableWithinBudget oldRoutes oldCost budget)
      (ReachableWithinBudget newRoutes newCost budget) := by
  refine ⟨routeDominates_preservesOn targets oldRoutes newRoutes
    oldCost newCost budget hdom, x, hxT, hOld, ?_⟩
  exact ⟨rNew, hrNew, hcostNew⟩

/-- Loss of any previously accessible declared target rules out preservation
and therefore rules out a strict monotone ratchet click. -/
theorem not_preservesOn_of_lost_target
    (targets : Set α) (oldAccess newAccess : α → Prop)
    (x : α) (hxT : x ∈ targets)
    (hOld : oldAccess x) (hNew : ¬ newAccess x) :
    ¬ PreservesOn targets oldAccess newAccess := by
  intro h
  exact hNew (h x hxT hOld)

#print axioms preservesOn_iff_subset
#print axioms strictExpandsOn_iff_ssubset
#print axioms preservesOn_refl
#print axioms preservesOn_trans
#print axioms strictExpandsOn_trans_preserves
#print axioms preserves_trans_strictExpandsOn
#print axioms strictExpandsOn_trans
#print axioms scoreDominates_preservesOn
#print axioms strictExpandsOn_of_score_crossing
#print axioms costDominates_preservesOn
#print axioms strictExpandsOn_of_cost_crossing
#print axioms exists_strictCostDominatingStep
#print axioms not_costDominates_scaled
#print axioms margin_nonneg
#print axioms margin_ratio
#print axioms margin_update
#print axioms winds_iff_binding_cost_falls
#print axioms accepted_fraction_margin_positive
#print axioms margin_dilute
#print axioms retainsCostOn_scaled_iff_margin
#print axioms margin_increase_opens_coupling_window
#print axioms coupling_between_margins_switches_retention
#print axioms production_increase_opens_threshold_window
#print axioms exact_two_click_witness
#print axioms exact_second_click_unavailable_at_baseline
#print axioms exact_first_click_winds
#print axioms exact_second_coupling_in_opened_window
#print axioms exact_second_threshold_in_opened_window
#print axioms exact_productive_extension_strictly_dominates
#print axioms exact_productive_extension_winds_margin
#print axioms routeDominatesOn_refl
#print axioms routeDominatesOn_trans
#print axioms routeDominates_preservesOn
#print axioms strictExpandsOn_of_new_route
#print axioms not_preservesOn_of_lost_target

end CumulativeAccessibility
