# Disable the default Minima theme
theme: null

# Use the Just the Docs theme from its GitHub repository
remote_theme: pmarsceill/just-the-docs

# Site settings
title: Evolution by Emergence
logo: assets/images/logo.png  # remove or adjust if you don’t have a logo
search: true

# Manually define the sidebar in the exact order you want
navigation:
  - title: Front Matter
    items:
      - title: Preface
        url: Frontmatter/Preface.md
      - title: Writing Process
        url: Frontmatter/Writing_process.md

  - title: Chapters
    items:
      - title: Chapter 1
        url: Chapters/Chapter_1.md
      - title: Chapter 2
        url: Chapters/Chapter_2.md
      - title: Chapter 3
        url: Chapters/Chapter_3.md
      - title: Chapter 4
        url: Chapters/Chapter_4.md
      - title: Chapter 5
        url: Chapters/Chapter_5.md
      - title: Chapter 6
        url: Chapters/Chapter_6.md
      - title: Chapter 7
        url: Chapters/Chapter_7.md
      - title: Chapter 8
        url: Chapters/Chapter_8.md
      - title: Chapter 9
        url: Chapters/Chapter_9.md
      - title: Chapter 10
        url: Chapters/Chapter_10.md
      - title: Chapter 11
        url: Chapters/Chapter_11.md
      - title: Chapter 12
        url: Chapters/Chapter_12.md
      - title: Chapter 13
        url: Chapters/Chapter_13.md

  - title: Back Matter
    items:
      - title: Epilogue
        url: Backmatter/Epilogue.md
      - title: Appendix
        url: Backmatter/Appendix.md
      - title: Literature
        url: Backmatter/Literature.md
      - title: Bibliography
        url: Backmatter/Bibliography.md

      - title: Cover
        url: Frontmatter/Cover.md 
      - title: Introduction
        url: Frontmatter/Introduction.md       # explicitly list it
      - title: How to Compile
        url: Frontmatter/Instructions_to_compile_the_book.md
