import CumulativeAccessibility
import CumulativeAccessibility.RecursiveAccessibility
import CumulativeAccessibility.EvolvabilityStructure
import CumulativeAccessibility.GenerativeArity
import CumulativeAccessibility.EmergentCapacity
import CumulativeAccessibility.VocabularyEmergence
import CumulativeAccessibility.EmergencePersistenceBridge
import CumulativeAccessibility.RecursiveEmergence
import CumulativeAccessibility.RecursiveEmergenceOpenEnded
import CumulativeAccessibility.SelfMaintenanceLeverage
import CumulativeAccessibility.EmergenceReproduction
import CumulativeAccessibility.EvolutionByEmergenceCore
import CumulativeAccessibility.GenerativeClosure
import CumulativeAccessibility.ModuleGeneratedEvolvability
import CumulativeAccessibility.GeneratorRuleEvolution
import CumulativeAccessibility.FiniteGenerativeSaturation
import CumulativeAccessibility.OpenEndedCapacity
import CumulativeAccessibility.CapacityUptake
import CumulativeAccessibility.CapacitySlack
import CumulativeAccessibility.ValidatedUptake
import CumulativeAccessibility.MaintenanceOpportunityBridge
import CumulativeAccessibility.ResponseDynamics
import CumulativeAccessibility.EndogenousBudgetBridge
import CumulativeAccessibility.FormalCoreWitness
import CumulativeAccessibility.MaintenanceGatedWitness
import CumulativeAccessibility.BoundedResponseWitness
import CumulativeAccessibility.EndogenousBudgetWitness
import CumulativeAccessibility.DynamicVortex
import CumulativeAccessibility.DynamicVortexWitness
import CumulativeAccessibility.QuantitativeAccessibility
import CumulativeAccessibility.IntelligentLearningMaintenance
import CumulativeAccessibility.FunctionalRatchetVelocity
import CumulativeAccessibility.RatchetVelocityLedger
import CumulativeAccessibility.BoundedUpdateRate
import CumulativeAccessibility.SearchValidationTradeoff
import CumulativeAccessibility.StateDependentAllocation
import CumulativeAccessibility.BottleneckAllocation
import CumulativeAccessibility.AdaptiveRatePolicy
import CumulativeAccessibility.ConstrainedRatePolicy
import CumulativeAccessibility.ClosedLoopRateControl
import CumulativeAccessibility.FunctionalRatePolicy
import CumulativeAccessibility.PolicyImprovement
import CumulativeAccessibility.PolicyLearning
import CumulativeAccessibility.RateRegret

/-!
# Aggregate package audit target

This module intentionally imports every module advertised by the cumulative
accessibility package README. Its role is verification coverage, not theorem
composition: if an advertised module stops compiling, this target must fail.
-/
