import CumulativeAccessibility.FunctionalRatchetVelocity

namespace CumulativeAccessibility
namespace IntelligentLearning

open RecursiveAccessibility
open FunctionalOrganization

variable {α P I : Type*}

/-!
# Intelligent learning-maintenance specialization

QuantitativeAccessibility.lean is the substrate-independent outside theory:
organization induces a directed accessibility-cost geometry, and retained change
can alter that geometry.

This file adds a separate inside description for intelligent learning
networks. It does not place honesty, correction, repair, or forgiveness into the
universal EbE theorem. Instead it provides an interface through which
substrate-specific learning processes can induce changes in the universal cost
geometry.

The distinction is:

* P — internal learning-maintenance process state;
* Γ : P → AccessibilityCost α — map from process state to the externally
  observed accessibility geometry;
* process interventions — substrate-specific operations that may change P.

An application may interpret process changes through verbs such as seeking,
testing, correcting, repairing, re-engaging, retaining, and recombining. No
universal monotonic effect of any verb is assumed here.
-/

/-- Internal verbs available to an intelligent learning network.

The constructors are descriptive labels only. Their causal effect is supplied
by an application-specific transition relation. -/
inductive LearningVerb
  | seek
  | listen
  | signalFaithfully
  | exposeUncertainty
  | test
  | revise
  | maintainEdge
  | repair
  | reengage
  | retain
  | recombine
  deriving DecidableEq, Repr

/-- A process state induces an externally measurable accessibility-cost
geometry. -/
abbrev ProcessGeometry (P α : Type*) :=
  P → AccessibilityCost α

/-- Application-specific internal transition produced by a learning verb. -/
abbrev AppliesVerb (P : Type*) :=
  P → LearningVerb → P → Prop

/-- An internal process transition is an accessibility improvement when its
induced outside geometry is strictly less viscous on the declared target set. -/
def ProcessImprovementOn
    (targets : Set α)
    (Γ : ProcessGeometry P α)
    (oldState newState : α)
    (oldProcess newProcess : P) : Prop :=
  StrictlyLessViscousOn targets
    (Γ oldProcess) (Γ newProcess)
    oldState newState

/-- A verb-level improvement: the application declares that the verb caused the
process transition, and the induced external geometry strictly improved. -/
def VerbImprovementOn
    (targets : Set α)
    (Γ : ProcessGeometry P α)
    (ApplyVerb : AppliesVerb P)
    (oldState newState : α)
    (oldProcess newProcess : P)
    (verb : LearningVerb) : Prop :=
  ApplyVerb oldProcess verb newProcess ∧
    ProcessImprovementOn targets Γ
      oldState newState oldProcess newProcess

/-- Any internally described process improvement has an externally observable
target whose declared future transition cost is lower. -/
theorem processImprovement_has_cheaper_future
    (targets : Set α)
    (Γ : ProcessGeometry P α)
    (oldState newState : α)
    (oldProcess newProcess : P)
    (h :
      ProcessImprovementOn targets Γ
        oldState newState oldProcess newProcess) :
    ∃ z, z ∈ targets ∧
      Γ newProcess newState z <
        Γ oldProcess oldState z := by
  exact h.2

/-- Any verb-level improvement opens a budget threshold at which some target is
unaffordable under the old process/organization and affordable under the new
one. -/
theorem verbImprovement_opens_budget_window
    (targets : Set α)
    (Γ : ProcessGeometry P α)
    (ApplyVerb : AppliesVerb P)
    (oldState newState : α)
    (oldProcess newProcess : P)
    (verb : LearningVerb)
    (h :
      VerbImprovementOn targets Γ ApplyVerb
        oldState newState oldProcess newProcess verb) :
    ∃ z B,
      z ∈ targets ∧
      ¬ AccessibleWithin
        (Γ oldProcess) B oldState z ∧
      AccessibleWithin
        (Γ newProcess) B newState z := by
  exact strictlyLessViscousOn_opens_budget_window
    targets (Γ oldProcess) (Γ newProcess)
    oldState newState h.2

/-- The system generates candidate interventions on its own learning-maintenance
process. This is intentionally more demanding than ordinary learning: the
intervention must be generated by the old process, applied to that process, and
produce a strict improvement in the induced accessibility geometry. -/
def SelfImprovementOn
    (targets : Set α)
    (Γ : ProcessGeometry P α)
    (Generate : P → I → Prop)
    (Apply : P → I → P → Prop)
    (oldState newState : α)
    (oldProcess newProcess : P) : Prop :=
  ∃ intervention,
    Generate oldProcess intervention ∧
    Apply oldProcess intervention newProcess ∧
    ProcessImprovementOn targets Γ
      oldState newState oldProcess newProcess

/-- Self-improvement has the same externally checkable quantitative
consequence: at least one declared future transition is strictly cheaper. -/
theorem selfImprovement_has_cheaper_future
    (targets : Set α)
    (Γ : ProcessGeometry P α)
    (Generate : P → I → Prop)
    (Apply : P → I → P → Prop)
    (oldState newState : α)
    (oldProcess newProcess : P)
    (h :
      SelfImprovementOn targets Γ Generate Apply
        oldState newState oldProcess newProcess) :
    ∃ z, z ∈ targets ∧
      Γ newProcess newState z <
        Γ oldProcess oldState z := by
  rcases h with ⟨intervention, hGen, hApply, hImprove⟩
  exact processImprovement_has_cheaper_future
    targets Γ oldState newState oldProcess newProcess hImprove

/-- A declared productivity functional measures how effective a process state is
at generating further successful process improvements. The formal theory does
not prescribe a universal empirical estimator for this quantity. -/
abbrev ImprovementProductivity (P : Type*) := P → ℝ

/-- Recursive self-improvement: an endogenous self-improvement also increases a
declared measure of the system's capacity to generate further improvements of
its learning-maintenance process.

This is a definition, not a theorem that self-improvement is necessarily
recursive or accelerating. -/
def RecursiveSelfImprovementOn
    (targets : Set α)
    (Γ : ProcessGeometry P α)
    (Generate : P → I → Prop)
    (Apply : P → I → P → Prop)
    (ρ : ImprovementProductivity P)
    (oldState newState : α)
    (oldProcess newProcess : P) : Prop :=
  SelfImprovementOn targets Γ Generate Apply
      oldState newState oldProcess newProcess ∧
    ρ oldProcess < ρ newProcess

theorem recursiveSelfImprovement_implies_selfImprovement
    (targets : Set α)
    (Γ : ProcessGeometry P α)
    (Generate : P → I → Prop)
    (Apply : P → I → P → Prop)
    (ρ : ImprovementProductivity P)
    (oldState newState : α)
    (oldProcess newProcess : P)
    (h :
      RecursiveSelfImprovementOn targets Γ Generate Apply ρ
        oldState newState oldProcess newProcess) :
    SelfImprovementOn targets Γ Generate Apply
      oldState newState oldProcess newProcess :=
  h.1

theorem recursiveSelfImprovement_increases_productivity
    (targets : Set α)
    (Γ : ProcessGeometry P α)
    (Generate : P → I → Prop)
    (Apply : P → I → P → Prop)
    (ρ : ImprovementProductivity P)
    (oldState newState : α)
    (oldProcess newProcess : P)
    (h :
      RecursiveSelfImprovementOn targets Γ Generate Apply ρ
        oldState newState oldProcess newProcess) :
    ρ oldProcess < ρ newProcess :=
  h.2

/-!
## Functional-rate grounding

The generic `ImprovementProductivity` interface above is intentionally
permissive. The functional-ratchet layer now supplies a stronger operational
specialization.

To test whether a process change improves the *speed of learning*, start matched
episodes from the same organizational state, use the same held-out functional
target family, normalize by each episode's declared positive duration/resource
interval, and compare the resulting rate profiles.

This is a counterfactual experimental definition, not a theorem that any named
learning verb has the desired effect.
-/

section FunctionalRateGrounding

variable {σ φ : Type*}

/-- An intelligent process state induces a cost geometry over functional
targets, which need not be the same type as organizational states. -/
abbrev FunctionalProcessGeometry (P σ φ : Type*) :=
  P → FunctionalCost σ φ

/-- The new process learns faster on a matched held-out episode: both episodes
start from the same organization, use positive declared intervals, and the new
process's normalized functional-rate profile strictly dominates the old one. -/
def MatchedLearningRateImprovementOn
    (learningTargets : Set φ)
    (Γ : FunctionalProcessGeometry P σ φ)
    (start oldEnd newEnd : σ)
    (oldDuration newDuration : ℝ)
    (oldProcess newProcess : P) : Prop :=
  0 < oldDuration ∧
  0 < newDuration ∧
  StrictlyFasterFunctionalRateOn learningTargets
    (Γ oldProcess) (Γ oldProcess)
    (Γ newProcess) (Γ newProcess)
    start oldEnd start newEnd
    oldDuration newDuration

/-- Rate-grounded recursive self-improvement.

The old process must generate and apply the intervention that creates the new
process. At the common starting organization, the process change must preserve
the declared retained functions, and on matched held-out learning episodes the
new process must achieve a strictly better normalized functional acquisition
rate profile.

The environmental matching needed for a real experiment remains
application-specific and is not encoded by the bare state type. -/
def RateGroundedRecursiveSelfImprovementOn
    (retainedTargets learningTargets : Set φ)
    (Γ : FunctionalProcessGeometry P σ φ)
    (Generate : P → I → Prop)
    (Apply : P → I → P → Prop)
    (start oldEnd newEnd : σ)
    (oldDuration newDuration : ℝ)
    (oldProcess newProcess : P) : Prop :=
  ∃ intervention,
    Generate oldProcess intervention ∧
    Apply oldProcess intervention newProcess ∧
    NoMoreFunctionallyViscousOn retainedTargets
      (Γ oldProcess) (Γ newProcess) start start ∧
    MatchedLearningRateImprovementOn learningTargets Γ
      start oldEnd newEnd
      oldDuration newDuration
      oldProcess newProcess

theorem rateGroundedRecursiveSelfImprovement_preserves_retained_functions
    (retainedTargets learningTargets : Set φ)
    (Γ : FunctionalProcessGeometry P σ φ)
    (Generate : P → I → Prop)
    (Apply : P → I → P → Prop)
    (start oldEnd newEnd : σ)
    (oldDuration newDuration : ℝ)
    (oldProcess newProcess : P)
    (h : RateGroundedRecursiveSelfImprovementOn
      retainedTargets learningTargets Γ Generate Apply
      start oldEnd newEnd oldDuration newDuration
      oldProcess newProcess) :
    NoMoreFunctionallyViscousOn retainedTargets
      (Γ oldProcess) (Γ newProcess) start start := by
  rcases h with ⟨intervention, hGen, hApply, hRetain, hRate⟩
  exact hRetain

theorem rateGroundedRecursiveSelfImprovement_has_faster_learning_target
    (retainedTargets learningTargets : Set φ)
    (Γ : FunctionalProcessGeometry P σ φ)
    (Generate : P → I → Prop)
    (Apply : P → I → P → Prop)
    (start oldEnd newEnd : σ)
    (oldDuration newDuration : ℝ)
    (oldProcess newProcess : P)
    (h : RateGroundedRecursiveSelfImprovementOn
      retainedTargets learningTargets Γ Generate Apply
      start oldEnd newEnd oldDuration newDuration
      oldProcess newProcess) :
    ∃ target, target ∈ learningTargets ∧
      FunctionalStepRate
          (Γ oldProcess) (Γ oldProcess)
          start oldEnd oldDuration target <
        FunctionalStepRate
          (Γ newProcess) (Γ newProcess)
          start newEnd newDuration target := by
  rcases h with ⟨intervention, hGen, hApply, hRetain, hRate⟩
  exact strictlyFasterFunctionalRate_has_target
    learningTargets
    (Γ oldProcess) (Γ oldProcess)
    (Γ newProcess) (Γ newProcess)
    start oldEnd start newEnd
    oldDuration newDuration hRate.2.2

end FunctionalRateGrounding

/-!
The mathematical content of this specialization is intentionally modest. Its
purpose is to preserve the two-level architecture:

OUTSIDE:
  process change -> changed accessibility-cost geometry.

INSIDE:
  an intelligent network can describe or generate process changes through
  substrate-specific actions/verbs.

Claims such as "honesty lowers corrective viscosity" or "repair preserves
valuable information edges" require an empirical or mechanistic model that maps
those processes into Γ; they are not universal consequences of EbE.
-/

#print axioms processImprovement_has_cheaper_future
#print axioms verbImprovement_opens_budget_window
#print axioms selfImprovement_has_cheaper_future
#print axioms recursiveSelfImprovement_implies_selfImprovement
#print axioms recursiveSelfImprovement_increases_productivity
#print axioms rateGroundedRecursiveSelfImprovement_preserves_retained_functions
#print axioms rateGroundedRecursiveSelfImprovement_has_faster_learning_target

end IntelligentLearning
end CumulativeAccessibility
