import CumulativeAccessibility.RetainedOrganizationCore
import Mathlib.Tactic

namespace CumulativeAccessibility
namespace TransitionAccessibility

/-!
# Transition machinery induces accessibility

This module closes the main semantic seam identified in the PR64 quality audit:
accessibility is no longer an arbitrary function independent of transition
machinery.

A weighted transition kernel declares which one-step transitions are available
and what they cost. Finite-horizon accessibility is then defined from routes
through that kernel. A retained kernel that preserves every old transition and
never raises its cost cannot reduce accessibility at a fixed free budget.

Maintenance is subsequently charged from the same gross budget. Therefore any
paid opening is attributable to the changed transition machinery overcoming its
own retention burden, rather than to an independently chosen accessibility
function.
-/

variable {σ R X : Type*}

/-- Weighted directed transition machinery. The allowed relation says the
transition exists; cost gives its one-step resource cost when it exists. -/
structure WeightedKernel (σ : Type*) where
  allowed : σ → σ → Prop
  cost : σ → σ → ℝ
  cost_nonneg : ∀ u v, allowed u v → 0 ≤ cost u v

/-- A route of exactly n transitions generated by a weighted kernel. -/
inductive Route (K : WeightedKernel σ) : σ → σ → ℕ → Type _
  | stay (s : σ) : Route K s s 0
  | step {s m y : σ} {n : ℕ} :
      K.allowed s m →
      Route K m y n →
      Route K s y (n + 1)

/-- Total transition cost of a generated route. -/
def Route.cost
    {K : WeightedKernel σ} {s y : σ} {n : ℕ} :
    Route K s y n → ℝ
  | .stay _ => 0
  | @Route.step _ _ s m y n hEdge rest => K.cost s m + rest.cost

/-- Target y is accessible from s within T transitions and free budget B, as
witnessed by an actual route generated by K. -/
def ReachableWithin
    (K : WeightedKernel σ)
    (T : ℕ)
    (B : ℝ)
    (s y : σ) : Prop :=
  ∃ n, n ≤ T ∧
    ∃ route : Route K s y n,
      route.cost ≤ B

/-- Accessibility is monotone in available free budget. -/
theorem reachableWithin_mono_budget
    (K : WeightedKernel σ)
    (T : ℕ)
    (B₁ B₂ : ℝ)
    (s y : σ)
    (hB : B₁ ≤ B₂)
    (hReach : ReachableWithin K T B₁ s y) :
    ReachableWithin K T B₂ s y := by
  rcases hReach with ⟨n, hn, route, hCost⟩
  exact ⟨n, hn, route, le_trans hCost hB⟩

/-- Kplus dominates Kminus when it preserves every transition available under
Kminus and makes every such transition no more costly. It may also add new
transitions. -/
structure KernelDominates
    (Kplus Kminus : WeightedKernel σ) : Prop where
  preserves :
    ∀ u v, Kminus.allowed u v → Kplus.allowed u v
  noMoreCostly :
    ∀ u v (h : Kminus.allowed u v),
      Kplus.cost u v ≤ Kminus.cost u v

/-- Every old route has a route with the same endpoints and number of steps
under a dominating kernel. -/
def liftRoute
    {Kplus Kminus : WeightedKernel σ}
    (hDom : KernelDominates Kplus Kminus)
    {s y : σ} {n : ℕ} :
    Route Kminus s y n →
    Route Kplus s y n
  | .stay s => .stay s
  | .step hEdge rest =>
      .step (hDom.preserves _ _ hEdge) (liftRoute hDom rest)

/-- Lifting a route into a dominating kernel cannot increase route cost. -/
theorem liftRoute_cost_le
    {Kplus Kminus : WeightedKernel σ}
    (hDom : KernelDominates Kplus Kminus)
    {s y : σ} {n : ℕ}
    (route : Route Kminus s y n) :
    (liftRoute hDom route).cost ≤ route.cost := by
  induction route with
  | stay s =>
      simp [liftRoute, Route.cost]
  | @step s m y n hEdge rest ih =>
      simp only [liftRoute, Route.cost]
      exact add_le_add
        (hDom.noMoreCostly s m hEdge)
        ih

/-- Transition dominance induces accessibility dominance at the same horizon and
free budget. This is the central K -> A theorem. -/
theorem kernelDominance_preserves_accessibility
    (Kplus Kminus : WeightedKernel σ)
    (hDom : KernelDominates Kplus Kminus)
    (T : ℕ)
    (B : ℝ)
    (s y : σ)
    (hReach : ReachableWithin Kminus T B s y) :
    ReachableWithin Kplus T B s y := by
  rcases hReach with ⟨n, hn, route, hCost⟩
  refine ⟨n, hn, liftRoute hDom route, ?_⟩
  exact le_trans (liftRoute_cost_le hDom route) hCost

/-- Retained organization selects the effective transition machinery. -/
abbrev KernelOf (R σ : Type*) := R → WeightedKernel σ

/-- Paid finite-horizon accessibility induced by retained transition machinery.
Maintenance is subtracted from the same gross budget before route reachability
is evaluated. -/
def PaidReachableWithin
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (grossBudget : ℝ)
    (r : R)
    (s y : σ) : Prop :=
  ReachableWithin
    (Kernel r)
    T
    (grossBudget - M r)
    s y

/-- At equal free budget, a dominating retained kernel cannot lose access. -/
theorem retainedKernelDominance_preserves_access_at_equal_freeBudget
    (Kernel : KernelOf R σ)
    (rPlus rMinus : R)
    (hDom : KernelDominates (Kernel rPlus) (Kernel rMinus))
    (T : ℕ)
    (freeBudget : ℝ)
    (s y : σ)
    (hReach :
      ReachableWithin (Kernel rMinus) T freeBudget s y) :
    ReachableWithin (Kernel rPlus) T freeBudget s y := by
  exact kernelDominance_preserves_accessibility
    (Kernel rPlus) (Kernel rMinus)
    hDom T freeBudget s y hReach

/-- A paid opening at one common gross budget. This is the induced-accessibility
version of the PR64 paid-transfer instrument. -/
def PositivePaidOpening
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (grossBudget : ℝ)
    (rMinus rPlus : R)
    (s y : σ) : Prop :=
  ¬ PaidReachableWithin Kernel M T grossBudget rMinus s y ∧
    PaidReachableWithin Kernel M T grossBudget rPlus s y

/-- **Paid opening requires a genuine retained-kernel advantage.**

If the retained arm pays at least as much upkeep as the ablated arm, positive
paid opening is impossible when the ablated kernel can reproduce every retained
transition at equal or lower cost. This strengthens the older equality-only
regression theorem: the kernels need not be identical for transfer to be ruled
out. -/
theorem positivePaidOpening_requires_kernel_advantage
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (grossBudget : ℝ)
    (rMinus rPlus : R)
    (s y : σ)
    (hUpkeep : M rMinus ≤ M rPlus)
    (hOpening :
      PositivePaidOpening
        Kernel M T grossBudget rMinus rPlus s y) :
    ¬ KernelDominates (Kernel rMinus) (Kernel rPlus) := by
  intro hDom
  rcases hOpening with ⟨hMinusClosed, hPlusOpen⟩
  unfold PaidReachableWithin at hMinusClosed hPlusOpen
  have hAtPlusBudget :
      ReachableWithin
        (Kernel rMinus) T
        (grossBudget - M rPlus)
        s y :=
    kernelDominance_preserves_accessibility
      (Kernel rMinus)
      (Kernel rPlus)
      hDom T
      (grossBudget - M rPlus)
      s y hPlusOpen
  have hBudget :
      grossBudget - M rPlus ≤ grossBudget - M rMinus := by
    linarith
  have hMinusOpen :=
    reachableWithin_mono_budget
      (Kernel rMinus) T
      (grossBudget - M rPlus)
      (grossBudget - M rMinus)
      s y hBudget hAtPlusBudget
  exact hMinusClosed hMinusOpen

/-- If an actual route made possible or cheap enough by the retained kernel fits
inside the retained arm's post-maintenance budget, while the ablated kernel has
no route within its own post-maintenance budget, then the same gross budget
exhibits positive paid opening.

Unlike the old free-accessibility interface, both sides are derived from their
transition kernels. -/
theorem route_advantage_overcomes_upkeep
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T n : ℕ)
    (grossBudget : ℝ)
    (rMinus rPlus : R)
    (s y : σ)
    (routePlus : Route (Kernel rPlus) s y n)
    (hn : n ≤ T)
    (hFits :
      routePlus.cost ≤ grossBudget - M rPlus)
    (hMinusClosed :
      ¬ ReachableWithin
        (Kernel rMinus) T
        (grossBudget - M rMinus)
        s y) :
    PositivePaidOpening
      Kernel M T grossBudget
      rMinus rPlus s y := by
  refine ⟨hMinusClosed, ?_⟩
  exact ⟨n, hn, routePlus, hFits⟩

/-- A lower bound on the cost of every route to one target within a finite
horizon under one kernel. -/
def RouteCostLowerBound
    (K : WeightedKernel σ)
    (T : ℕ)
    (s y : σ)
    (L : ℝ) : Prop :=
  ∀ n, n ≤ T →
    ∀ route : Route K s y n,
      L ≤ route.cost

/-- Quantitative paid-transfer theorem.

Suppose the retained arm has an actual route of cost Cplus, every ablated route
within the same horizon costs at least Lminus, and the retained route's saving
exceeds the marginal maintenance burden:

    Cplus + (Mplus - Mminus) < Lminus.

Then there exists a common gross budget at which the target is inaccessible
without the retained organization and accessible with it. The proof chooses the
gross budget Cplus + Mplus.

This is the induced-kernel form of "transition advantage exceeds upkeep". -/
theorem route_saving_exceeds_marginal_upkeep_opens_paid_window
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T n : ℕ)
    (rMinus rPlus : R)
    (s y : σ)
    (routePlus : Route (Kernel rPlus) s y n)
    (hn : n ≤ T)
    (Lminus : ℝ)
    (hLower :
      RouteCostLowerBound
        (Kernel rMinus) T s y Lminus)
    (hMargin :
      routePlus.cost + (M rPlus - M rMinus) < Lminus) :
    ∃ grossBudget,
      PositivePaidOpening
        Kernel M T grossBudget
        rMinus rPlus s y := by
  let grossBudget : ℝ := routePlus.cost + M rPlus
  refine ⟨grossBudget, ?_, ?_⟩
  · intro hMinus
    rcases hMinus with ⟨m, hm, routeMinus, hMinusCost⟩
    have hLB : Lminus ≤ routeMinus.cost :=
      hLower m hm routeMinus
    dsimp [PaidReachableWithin, grossBudget] at hMinusCost
    linarith
  · refine ⟨n, hn, routePlus, ?_⟩
    dsimp [grossBudget]
    linarith

/-- Item-specific induced paid opening. Both retained repertoires are generated
from the same baseline repertoire and the same retained item X. -/
def PositivePaidOpeningForItem
    (Retain : RetainedOrganizationCore.RetainItem R X)
    (Lose : RetainedOrganizationCore.LoseItem R X)
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (grossBudget : ℝ)
    (baseRetained : R)
    (x : X)
    (s y : σ) : Prop :=
  PositivePaidOpening
    Kernel M T grossBudget
    (Lose baseRetained x)
    (Retain baseRetained x)
    s y

/-- Item-specific form of the route-saving theorem. -/
theorem item_route_saving_exceeds_marginal_upkeep_opens_paid_window
    (Retain : RetainedOrganizationCore.RetainItem R X)
    (Lose : RetainedOrganizationCore.LoseItem R X)
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T n : ℕ)
    (baseRetained : R)
    (x : X)
    (s y : σ)
    (routePlus :
      Route (Kernel (Retain baseRetained x)) s y n)
    (hn : n ≤ T)
    (Lminus : ℝ)
    (hLower :
      RouteCostLowerBound
        (Kernel (Lose baseRetained x))
        T s y Lminus)
    (hMargin :
      routePlus.cost +
          (M (Retain baseRetained x) -
            M (Lose baseRetained x)) <
        Lminus) :
    ∃ grossBudget,
      PositivePaidOpeningForItem
        Retain Lose Kernel M T grossBudget
        baseRetained x s y := by
  exact route_saving_exceeds_marginal_upkeep_opens_paid_window
    Kernel M T n
    (Lose baseRetained x)
    (Retain baseRetained x)
    s y routePlus hn Lminus hLower hMargin

/-- Route-level paid opening for one identified retained item. -/
theorem item_route_advantage_overcomes_upkeep
    (Retain : RetainedOrganizationCore.RetainItem R X)
    (Lose : RetainedOrganizationCore.LoseItem R X)
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T n : ℕ)
    (grossBudget : ℝ)
    (baseRetained : R)
    (x : X)
    (s y : σ)
    (routePlus :
      Route (Kernel (Retain baseRetained x)) s y n)
    (hn : n ≤ T)
    (hFits :
      routePlus.cost ≤
        grossBudget - M (Retain baseRetained x))
    (hMinusClosed :
      ¬ ReachableWithin
        (Kernel (Lose baseRetained x)) T
        (grossBudget - M (Lose baseRetained x))
        s y) :
    PositivePaidOpeningForItem
      Retain Lose Kernel M T grossBudget
      baseRetained x s y := by
  exact route_advantage_overcomes_upkeep
    Kernel M T n grossBudget
    (Lose baseRetained x)
    (Retain baseRetained x)
    s y routePlus hn hFits hMinusClosed

/-- Regression guard: if retained and ablated organization induce exactly the
same kernel and the retained arm has weakly less free budget, retaining cannot
create a paid opening. -/
theorem no_paidOpening_without_kernel_change
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (grossBudget : ℝ)
    (rMinus rPlus : R)
    (s y : σ)
    (hKernel : Kernel rPlus = Kernel rMinus)
    (hUpkeep : M rMinus ≤ M rPlus) :
    ¬ PositivePaidOpening
      Kernel M T grossBudget
      rMinus rPlus s y := by
  intro hOpening
  rcases hOpening with ⟨hMinusClosed, hPlusOpen⟩
  have hBudget :
      grossBudget - M rPlus ≤ grossBudget - M rMinus := by
    linarith
  unfold PaidReachableWithin at hMinusClosed hPlusOpen
  rw [hKernel] at hPlusOpen
  have hMinusOpen :=
    reachableWithin_mono_budget
      (Kernel rMinus) T
      (grossBudget - M rPlus)
      (grossBudget - M rMinus)
      s y hBudget hPlusOpen
  exact hMinusClosed hMinusOpen

/-! ## Bridge back to the retained-organization core

The generic core keeps `Accessibility` abstract so applications can use
probabilities, reliabilities, or other graded observables. For the universal
transition theorem surface, however, accessibility should be *induced* by the
declared transition machinery rather than supplied independently.

The following implementation embeds finite-horizon kernel reachability as a
0/1-valued core accessibility measure and proves that the core's paid-transfer
predicate is exactly retained reachability together with ablated
non-reachability at each arm's own post-maintenance budget.
-/

variable {G Γ : Type*}

/-- State-dependent weighted transition machinery for the core state variables. -/
abbrev CoreKernel (G R Γ σ : Type*) :=
  G → R → Γ → WeightedKernel σ

/-- Starting transition-state represented by the active organization. -/
abbrev StartOf (G σ : Type*) := G → σ

open Classical in
/-- Core accessibility induced by weighted transition reachability. -/
noncomputable def kernelAccessibility
    (KR : CoreKernel G R Γ σ)
    (startOf : StartOf G σ) :
    RetainedOrganizationCore.Accessibility G R Γ σ :=
  fun T g r γ b y =>
    if ReachableWithin (KR g r γ) T b (startOf g) y then 1 else 0

/-- Kernel-induced core accessibility is automatically monotone in free budget. -/
theorem kernelAccessibility_budgetMonotone
    (KR : CoreKernel G R Γ σ)
    (startOf : StartOf G σ) :
    RetainedOrganizationCore.BudgetMonotone
      (kernelAccessibility KR startOf) := by
  intro T g r γ y b₁ b₂ hb
  classical
  unfold kernelAccessibility
  by_cases h₁ : ReachableWithin (KR g r γ) T b₁ (startOf g) y
  · have h₂ :
        ReachableWithin (KR g r γ) T b₂ (startOf g) y :=
      reachableWithin_mono_budget
        (KR g r γ) T b₁ b₂ (startOf g) y hb h₁
    simp [h₁, h₂]
  · by_cases h₂ : ReachableWithin (KR g r γ) T b₂ (startOf g) y
    · simp [h₁, h₂]
    · simp [h₁, h₂]

/-- The generic core's positive transfer, when evaluated with
kernel-induced accessibility, is exactly a paid accessibility opening through
the state-dependent transition machinery. -/
theorem core_positiveTransfer_iff_kernel_reach
    (KR : CoreKernel G R Γ σ)
    (startOf : StartOf G σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (sMinus sPlus : RetainedOrganizationCore.State G R Γ)
    (y : σ) :
    RetainedOrganizationCore.PositiveTransferAt
        (kernelAccessibility KR startOf)
        M T sMinus sPlus y
      ↔
    (ReachableWithin
        (KR sPlus.active sPlus.retained sPlus.context)
        T
        (RetainedOrganizationCore.freeBudget M sPlus)
        (startOf sPlus.active) y ∧
      ¬ ReachableWithin
        (KR sMinus.active sMinus.retained sMinus.context)
        T
        (RetainedOrganizationCore.freeBudget M sMinus)
        (startOf sMinus.active) y) := by
  classical
  unfold RetainedOrganizationCore.PositiveTransferAt
    RetainedOrganizationCore.transferGain
    RetainedOrganizationCore.stateAccessibility
    kernelAccessibility
  by_cases hp :
      ReachableWithin
        (KR sPlus.active sPlus.retained sPlus.context)
        T
        (RetainedOrganizationCore.freeBudget M sPlus)
        (startOf sPlus.active) y <;>
  by_cases hm :
      ReachableWithin
        (KR sMinus.active sMinus.retained sMinus.context)
        T
        (RetainedOrganizationCore.freeBudget M sMinus)
        (startOf sMinus.active) y <;>
  simp [hp, hm]

/-- Item-specific version of the core bridge. The retained and ablated arms
come from the same base state and the same item `x`. -/
theorem core_positiveTransferForItem_iff_kernel_reach
    (Retain : RetainedOrganizationCore.RetainItem R X)
    (Lose : RetainedOrganizationCore.LoseItem R X)
    (KR : CoreKernel G R Γ σ)
    (startOf : StartOf G σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (base : RetainedOrganizationCore.State G R Γ)
    (x : X)
    (y : σ) :
    RetainedOrganizationCore.PositiveTransferForItem
        Retain Lose
        (kernelAccessibility KR startOf)
        M T base x y
      ↔
    (ReachableWithin
        (KR base.active (Retain base.retained x) base.context)
        T
        (RetainedOrganizationCore.freeBudget M
          (RetainedOrganizationCore.retainedArm Retain base x))
        (startOf base.active) y ∧
      ¬ ReachableWithin
        (KR base.active (Lose base.retained x) base.context)
        T
        (RetainedOrganizationCore.freeBudget M
          (RetainedOrganizationCore.ablatedArm Lose base x))
        (startOf base.active) y) := by
  simpa [RetainedOrganizationCore.PositiveTransferForItem,
    RetainedOrganizationCore.retainedArm,
    RetainedOrganizationCore.ablatedArm] using
    (core_positiveTransfer_iff_kernel_reach
      KR startOf M T
      (RetainedOrganizationCore.ablatedArm Lose base x)
      (RetainedOrganizationCore.retainedArm Retain base x)
      y)

/-- Once accessibility is induced by transition machinery, an item-specific
core paid-transfer result plus positive marginal upkeep certifies that the
ablated kernel cannot reproduce all retained transitions at equal or lower
cost. This closes the K-to-A-to-core loop. -/
theorem core_positiveTransferForItem_requires_kernel_advantage
    (Retain : RetainedOrganizationCore.RetainItem R X)
    (Lose : RetainedOrganizationCore.LoseItem R X)
    (KR : CoreKernel G R Γ σ)
    (startOf : StartOf G σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (base : RetainedOrganizationCore.State G R Γ)
    (x : X)
    (y : σ)
    (hPaid :
      RetainedOrganizationCore.StrictlyPaidItem
        Retain Lose M base x)
    (hTransfer :
      RetainedOrganizationCore.PositiveTransferForItem
        Retain Lose
        (kernelAccessibility KR startOf)
        M T base x y) :
    ¬ KernelDominates
        (KR base.active (Lose base.retained x) base.context)
        (KR base.active (Retain base.retained x) base.context) := by
  intro hDom
  have hReach :=
    (core_positiveTransferForItem_iff_kernel_reach
      Retain Lose KR startOf M T base x y).1 hTransfer
  have hBudget :
      RetainedOrganizationCore.freeBudget M
          (RetainedOrganizationCore.retainedArm Retain base x)
        ≤
      RetainedOrganizationCore.freeBudget M
          (RetainedOrganizationCore.ablatedArm Lose base x) :=
    le_of_lt
      (RetainedOrganizationCore.strictlyPaidItem_reduces_freeBudget
        Retain Lose M base x hPaid)
  have hMinusAtPlusBudget :
      ReachableWithin
        (KR base.active (Lose base.retained x) base.context)
        T
        (RetainedOrganizationCore.freeBudget M
          (RetainedOrganizationCore.retainedArm Retain base x))
        (startOf base.active) y :=
    kernelDominance_preserves_accessibility
      (KR base.active (Lose base.retained x) base.context)
      (KR base.active (Retain base.retained x) base.context)
      hDom T
      (RetainedOrganizationCore.freeBudget M
        (RetainedOrganizationCore.retainedArm Retain base x))
      (startOf base.active) y hReach.1
  have hMinus :
      ReachableWithin
        (KR base.active (Lose base.retained x) base.context)
        T
        (RetainedOrganizationCore.freeBudget M
          (RetainedOrganizationCore.ablatedArm Lose base x))
        (startOf base.active) y :=
    reachableWithin_mono_budget
      (KR base.active (Lose base.retained x) base.context)
      T
      (RetainedOrganizationCore.freeBudget M
        (RetainedOrganizationCore.retainedArm Retain base x))
      (RetainedOrganizationCore.freeBudget M
        (RetainedOrganizationCore.ablatedArm Lose base x))
      (startOf base.active) y hBudget hMinusAtPlusBudget
  exact hReach.2 hMinus

/-! ## Fully constructive paid-transfer witness -/

inductive RetainedKernelToyState
  | origin
  | target
  deriving DecidableEq

open RetainedKernelToyState

/-- Without the retained item there is no origin-to-target transition. With the
item, one unit-cost transition is available. -/
def retainedKernelToyKernel : Bool → WeightedKernel RetainedKernelToyState
  | false =>
      { allowed := fun _ _ => False
        cost := fun _ _ => 0
        cost_nonneg := by
          intro u v h
          contradiction }
  | true =>
      { allowed := fun u v => u = origin ∧ v = target
        cost := fun u v =>
          if u = origin ∧ v = target then 1 else 0
        cost_nonneg := by
          intro u v h
          simp [h] }

/-- Retaining the item costs one unit; the ablated repertoire costs zero. -/
def retainedKernelToyMaintenance : Bool → ℝ
  | false => 0
  | true => 1

def retainedKernelToyRetain : Bool → Unit → Bool :=
  fun _ _ => true

def retainedKernelToyLose : Bool → Unit → Bool :=
  fun _ _ => false

/-- The retained kernel has a one-step route to the target. -/
def retainedKernelToyRoute :
    Route (retainedKernelToyKernel true) origin target 1 :=
  .step (by simp [retainedKernelToyKernel])
    (.stay target)

/-- The ablated kernel cannot reach the target at any finite budget within one
step because it has no transitions at all. -/
theorem retainedKernelToy_ablated_not_reachable :
    ¬ ReachableWithin
      (retainedKernelToyKernel false)
      1 2 origin target := by
  intro h
  rcases h with ⟨n, hn, route, hCost⟩
  cases route with
  | step hEdge rest =>
      simp [retainedKernelToyKernel] at hEdge

/-- Concrete end-to-end witness: gross budget two, one unit of maintenance, and
a one-unit retained transition yield positive paid opening to the previously
unreachable target. -/
theorem retainedKernelToy_positive_item_paid_opening :
    PositivePaidOpeningForItem
      retainedKernelToyRetain
      retainedKernelToyLose
      retainedKernelToyKernel
      retainedKernelToyMaintenance
      1 2 false () origin target := by
  apply item_route_advantage_overcomes_upkeep
    retainedKernelToyRetain
    retainedKernelToyLose
    retainedKernelToyKernel
    retainedKernelToyMaintenance
    1 1 2 false () origin target
    retainedKernelToyRoute
  · norm_num
  · norm_num [retainedKernelToyRoute, Route.cost,
      retainedKernelToyKernel, retainedKernelToyMaintenance,
      retainedKernelToyRetain]
  · simpa [retainedKernelToyLose, retainedKernelToyMaintenance] using
      retainedKernelToy_ablated_not_reachable

#print axioms reachableWithin_mono_budget
#print axioms liftRoute_cost_le
#print axioms kernelDominance_preserves_accessibility
#print axioms retainedKernelDominance_preserves_access_at_equal_freeBudget
#print axioms positivePaidOpening_requires_kernel_advantage
#print axioms route_advantage_overcomes_upkeep
#print axioms route_saving_exceeds_marginal_upkeep_opens_paid_window
#print axioms item_route_saving_exceeds_marginal_upkeep_opens_paid_window
#print axioms item_route_advantage_overcomes_upkeep
#print axioms no_paidOpening_without_kernel_change
#print axioms kernelAccessibility_budgetMonotone
#print axioms core_positiveTransfer_iff_kernel_reach
#print axioms core_positiveTransferForItem_iff_kernel_reach
#print axioms core_positiveTransferForItem_requires_kernel_advantage
#print axioms retainedKernelToy_ablated_not_reachable
#print axioms retainedKernelToy_positive_item_paid_opening

end TransitionAccessibility
end CumulativeAccessibility
