import CumulativeAccessibility.RetainedOrganizationCore
import Mathlib.Tactic

namespace CumulativeAccessibility
namespace TransitionAccessibility

/-!
# Transition machinery induces accessibility

This module closes the main semantic seam identified in the PR64 quality audit:
accessibility is no longer an arbitrary function independent of transition
machinery.

A weighted transition kernel declares which one-step transitions are available
and what they cost. Finite-horizon accessibility is then defined from routes
through that kernel. A retained kernel that preserves every old transition and
never raises its cost cannot reduce accessibility at a fixed free budget.

Maintenance is subsequently charged from the same gross budget. Therefore any
paid opening is attributable to the changed transition machinery overcoming its
own retention burden, rather than to an independently chosen accessibility
function.
-/

variable {σ R : Type*}

/-- Weighted directed transition machinery. The allowed relation says the
transition exists; cost gives its one-step resource cost when it exists. -/
structure WeightedKernel (σ : Type*) where
  allowed : σ → σ → Prop
  cost : σ → σ → ℝ
  cost_nonneg : ∀ u v, allowed u v → 0 ≤ cost u v

/-- A route of exactly n transitions generated by a weighted kernel. -/
inductive Route (K : WeightedKernel σ) : σ → σ → ℕ → Type _
  | stay (s : σ) : Route K s s 0
  | step {s m y : σ} {n : ℕ} :
      K.allowed s m →
      Route K m y n →
      Route K s y (n + 1)

/-- Total transition cost of a generated route. -/
def Route.cost
    {K : WeightedKernel σ} {s y : σ} {n : ℕ} :
    Route K s y n → ℝ
  | .stay _ => 0
  | .step hEdge rest => K.cost _ _ + rest.cost

/-- Target y is accessible from s within T transitions and free budget B, as
witnessed by an actual route generated by K. -/
def ReachableWithin
    (K : WeightedKernel σ)
    (T : ℕ)
    (B : ℝ)
    (s y : σ) : Prop :=
  ∃ n, n ≤ T ∧
    ∃ route : Route K s y n,
      route.cost ≤ B

/-- Accessibility is monotone in available free budget. -/
theorem reachableWithin_mono_budget
    (K : WeightedKernel σ)
    (T : ℕ)
    (B₁ B₂ : ℝ)
    (s y : σ)
    (hB : B₁ ≤ B₂)
    (hReach : ReachableWithin K T B₁ s y) :
    ReachableWithin K T B₂ s y := by
  rcases hReach with ⟨n, hn, route, hCost⟩
  exact ⟨n, hn, route, le_trans hCost hB⟩

/-- Kplus dominates Kminus when it preserves every transition available under
Kminus and makes every such transition no more costly. It may also add new
transitions. -/
structure KernelDominates
    (Kplus Kminus : WeightedKernel σ) : Prop where
  preserves :
    ∀ u v, Kminus.allowed u v → Kplus.allowed u v
  noMoreCostly :
    ∀ u v (h : Kminus.allowed u v),
      Kplus.cost u v ≤ Kminus.cost u v

/-- Every old route has a route with the same endpoints and number of steps
under a dominating kernel. -/
def liftRoute
    {Kplus Kminus : WeightedKernel σ}
    (hDom : KernelDominates Kplus Kminus)
    {s y : σ} {n : ℕ} :
    Route Kminus s y n →
    Route Kplus s y n
  | .stay s => .stay s
  | .step hEdge rest =>
      .step (hDom.preserves _ _ hEdge) (liftRoute hDom rest)

/-- Lifting a route into a dominating kernel cannot increase route cost. -/
theorem liftRoute_cost_le
    {Kplus Kminus : WeightedKernel σ}
    (hDom : KernelDominates Kplus Kminus)
    {s y : σ} {n : ℕ}
    (route : Route Kminus s y n) :
    (liftRoute hDom route).cost ≤ route.cost := by
  induction route with
  | stay s =>
      simp [liftRoute, Route.cost]
  | @step s m y n hEdge rest ih =>
      simp only [liftRoute, Route.cost]
      exact add_le_add
        (hDom.noMoreCostly s m hEdge)
        ih

/-- Transition dominance induces accessibility dominance at the same horizon and
free budget. This is the central K -> A theorem. -/
theorem kernelDominance_preserves_accessibility
    (Kplus Kminus : WeightedKernel σ)
    (hDom : KernelDominates Kplus Kminus)
    (T : ℕ)
    (B : ℝ)
    (s y : σ)
    (hReach : ReachableWithin Kminus T B s y) :
    ReachableWithin Kplus T B s y := by
  rcases hReach with ⟨n, hn, route, hCost⟩
  refine ⟨n, hn, liftRoute hDom route, ?_⟩
  exact le_trans (liftRoute_cost_le hDom route) hCost

/-- Retained organization selects the effective transition machinery. -/
abbrev KernelOf (R σ : Type*) := R → WeightedKernel σ

/-- Paid finite-horizon accessibility induced by retained transition machinery.
Maintenance is subtracted from the same gross budget before route reachability
is evaluated. -/
def PaidReachableWithin
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (grossBudget : ℝ)
    (r : R)
    (s y : σ) : Prop :=
  ReachableWithin
    (Kernel r)
    T
    (grossBudget - M r)
    s y

/-- At equal free budget, a dominating retained kernel cannot lose access. -/
theorem retainedKernelDominance_preserves_access_at_equal_freeBudget
    (Kernel : KernelOf R σ)
    (rPlus rMinus : R)
    (hDom : KernelDominates (Kernel rPlus) (Kernel rMinus))
    (T : ℕ)
    (freeBudget : ℝ)
    (s y : σ)
    (hReach :
      ReachableWithin (Kernel rMinus) T freeBudget s y) :
    ReachableWithin (Kernel rPlus) T freeBudget s y := by
  exact kernelDominance_preserves_accessibility
    (Kernel rPlus) (Kernel rMinus)
    hDom T freeBudget s y hReach

/-- A paid opening at one common gross budget. This is the induced-accessibility
version of the PR64 paid-transfer instrument. -/
def PositivePaidOpening
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (grossBudget : ℝ)
    (rMinus rPlus : R)
    (s y : σ) : Prop :=
  ¬ PaidReachableWithin Kernel M T grossBudget rMinus s y ∧
    PaidReachableWithin Kernel M T grossBudget rPlus s y

/-- If an actual route made possible or cheap enough by the retained kernel fits
inside the retained arm's post-maintenance budget, while the ablated kernel has
no route within its own post-maintenance budget, then the same gross budget
exhibits positive paid opening.

Unlike the old free-accessibility interface, both sides are derived from their
transition kernels. -/
theorem route_advantage_overcomes_upkeep
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T n : ℕ)
    (grossBudget : ℝ)
    (rMinus rPlus : R)
    (s y : σ)
    (routePlus : Route (Kernel rPlus) s y n)
    (hn : n ≤ T)
    (hFits :
      routePlus.cost ≤ grossBudget - M rPlus)
    (hMinusClosed :
      ¬ ReachableWithin
        (Kernel rMinus) T
        (grossBudget - M rMinus)
        s y) :
    PositivePaidOpening
      Kernel M T grossBudget
      rMinus rPlus s y := by
  refine ⟨hMinusClosed, ?_⟩
  exact ⟨n, hn, routePlus, hFits⟩

/-- Regression guard: if retained and ablated organization induce exactly the
same kernel and the retained arm has weakly less free budget, retaining cannot
create a paid opening. -/
theorem no_paidOpening_without_kernel_change
    (Kernel : KernelOf R σ)
    (M : RetainedOrganizationCore.Maintenance R)
    (T : ℕ)
    (grossBudget : ℝ)
    (rMinus rPlus : R)
    (s y : σ)
    (hKernel : Kernel rPlus = Kernel rMinus)
    (hUpkeep : M rMinus ≤ M rPlus) :
    ¬ PositivePaidOpening
      Kernel M T grossBudget
      rMinus rPlus s y := by
  intro hOpening
  rcases hOpening with ⟨hMinusClosed, hPlusOpen⟩
  have hBudget :
      grossBudget - M rPlus ≤ grossBudget - M rMinus := by
    linarith
  rw [hKernel] at hPlusOpen
  have hMinusOpen :=
    reachableWithin_mono_budget
      (Kernel rMinus) T
      (grossBudget - M rPlus)
      (grossBudget - M rMinus)
      s y hBudget hPlusOpen
  exact hMinusClosed hMinusOpen

#print axioms reachableWithin_mono_budget
#print axioms liftRoute_cost_le
#print axioms kernelDominance_preserves_accessibility
#print axioms retainedKernelDominance_preserves_access_at_equal_freeBudget
#print axioms route_advantage_overcomes_upkeep
#print axioms no_paidOpening_without_kernel_change

end TransitionAccessibility
end CumulativeAccessibility
