import CumulativeAccessibility.AuditAll

/-!
# Explicit advertised-result axiom audit

Compilation and proof-dependency auditing are separate checks. AuditAll forces
all advertised modules through Lean; this file prints the axiom dependencies of
the declarations selected as the public verification surface. CI rejects any
printed dependency containing sorryAx.

The list is intentionally explicit so additions to the advertised result
surface require a reviewable change here.
-/

open CumulativeAccessibility
open CumulativeAccessibility.RecursiveAccessibility

#print axioms CollectiveAlignment.cycle3StateStep_preserves_canonical_lower_bound
#print axioms CollectiveAlignment.cycle3Trajectory_stays_above_canonical
#print axioms CollectiveAlignment.cycle3Trajectory_supported_by_canonical
#print axioms CollectiveAlignment.cycle3Trajectory_has_positive_support_floor
#print axioms CollectiveAlignment.cycle3_strict_loop_has_arbitrarily_late_availability

#print axioms CumulativeAccessibility.RecursiveAccessibility.emergentUnder_minimal_realizers_incomparable
#print axioms CumulativeAccessibility.RecursiveAccessibility.emergence_event_implies_generatedFromAvailable
#print axioms CumulativeAccessibility.RecursiveAccessibility.operational_vocabulary_ratchet_step
#print axioms CumulativeAccessibility.RecursiveAccessibility.resourceValidatedEmergentIntegration_implies_operationalExpansion
#print axioms CumulativeAccessibility.RecursiveAccessibility.resourceValidatedEmergentIntegration_with_generation_implies_resourceValidatedSuccessAt
#print axioms CumulativeAccessibility.RecursiveAccessibility.retainedIntegration_strictly_expands_next
#print axioms CumulativeAccessibility.RecursiveAccessibility.retainedIntegration_contains_minimal_operationalIntegration
#print axioms CumulativeAccessibility.RecursiveAccessibility.monotoneRetention_persistsFrom
#print axioms CumulativeAccessibility.RecursiveAccessibility.resourceValidatedEmergentIntegration_persists
#print axioms CumulativeAccessibility.RecursiveAccessibility.retainedRepertoire_with_new_downstream_strictly_expands_generation
#print axioms CumulativeAccessibility.RecursiveAccessibility.minimalIntegration_generation_lifts_to_retained_next
#print axioms CumulativeAccessibility.RecursiveAccessibility.resourceValidatedEmergentIntegration_operationalRatchet
#print axioms CumulativeAccessibility.RecursiveAccessibility.generatedUsingParent_implies_generatedFromAvailable
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveEmergenceStep_implies_generated
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveEmergenceStep_retains_new_child
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveEmergenceStep_strictly_expands_repertoire
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveEmergenceChain_endpoint_active
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveEmergenceChain_strict_at_each_link
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveToy_b_to_c_is_recursiveEmergenceStep
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveToy_two_event_recursive_emergence
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveToy_two_strict_expansions
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveEmergenceStep_with_envelope_implies_resourceValidatedSuccessAt
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringRecursiveEmergence_implies_validatedGenerativeCapacityUptake
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringRecursiveEmergence_gives_future_strict_step
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringRecursiveEmergence_implies_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringRecursiveEmergence_via_validatedUptake_implies_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringRecursiveEmergence_implies_unboundedEnvelope
#print axioms CumulativeAccessibility.RecursiveAccessibility.progressive_recursiveEmergenceStep
#print axioms CumulativeAccessibility.RecursiveAccessibility.progressive_has_recurringRecursiveEmergence
#print axioms CumulativeAccessibility.RecursiveAccessibility.progressive_has_recursiveEmergenceEnvelopeCoverage
#print axioms CumulativeAccessibility.RecursiveAccessibility.progressive_validatedUptake_via_recursiveEmergence
#print axioms CumulativeAccessibility.RecursiveAccessibility.progressive_openEnded_via_recursiveEmergence
#print axioms CumulativeAccessibility.RecursiveAccessibility.strict_slack_gain_is_budget_and_buffer_gain
#print axioms CumulativeAccessibility.RecursiveAccessibility.selfMaintenanceLeverage_preserves_slackFundedAccess
#print axioms CumulativeAccessibility.RecursiveAccessibility.selfMaintenanceLeverage_strictly_expands_with_witness
#print axioms CumulativeAccessibility.RecursiveAccessibility.lifetimeAdaptiveBudget_mono
#print axioms CumulativeAccessibility.RecursiveAccessibility.lifetimeAdaptiveBudget_strict_of_slack_gain
#print axioms CumulativeAccessibility.RecursiveAccessibility.recursiveEmergenceSuccessorWithin_iterates
#print axioms CumulativeAccessibility.RecursiveAccessibility.seed_and_successorWithin_imply_recurringRecursiveEmergence
#print axioms CumulativeAccessibility.RecursiveAccessibility.seed_and_successorWithin_imply_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.progressive_has_recursiveEmergenceSuccessorWithin_zero
#print axioms CumulativeAccessibility.RecursiveAccessibility.progressive_openEnded_via_local_chainReaction
#print axioms CumulativeAccessibility.RecursiveAccessibility.leverageToy_strict_access_expansion
#print axioms CumulativeAccessibility.RecursiveAccessibility.leverageToy_budget_and_buffer_gain
#print axioms CumulativeAccessibility.RecursiveAccessibility.one_le_effectiveEmergenceSuccessorCount_iff_exists
#print axioms CumulativeAccessibility.RecursiveAccessibility.one_le_effectiveEmergenceReproductionNumber_iff_exists
#print axioms CumulativeAccessibility.RecursiveAccessibility.supercritical_effectiveEmergenceReproduction_has_two_successors
#print axioms CumulativeAccessibility.RecursiveAccessibility.uniformCriticalEmergenceReproduction_implies_successorWithin_zero
#print axioms CumulativeAccessibility.RecursiveAccessibility.seed_and_uniformCriticalEmergenceReproduction_imply_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.emergenceReproductionLedger_nonneg
#print axioms CumulativeAccessibility.RecursiveAccessibility.emergenceReproductionLedger_mono_window
#print axioms CumulativeAccessibility.RecursiveAccessibility.emergenceReproductionLedger_mono_opportunity
#print axioms CumulativeAccessibility.RecursiveAccessibility.emergenceReproductionLedger_eq_window_mul_mechanisticRate
#print axioms CumulativeAccessibility.RecursiveAccessibility.emergenceReproductionLedger_mono_generation
#print axioms CumulativeAccessibility.RecursiveAccessibility.emergenceReproductionLedger_mono_resource
#print axioms CumulativeAccessibility.RecursiveAccessibility.emergenceReproductionLedger_mono_validation
#print axioms CumulativeAccessibility.RecursiveAccessibility.emergenceReproductionLedger_mono_retention
#print axioms CumulativeAccessibility.RecursiveAccessibility.certifiedLedger_at_least_one_implies_actual_at_least_one
#print axioms CumulativeAccessibility.RecursiveAccessibility.certifiedCriticalEmergenceEvent_implies_effective_successor




#print axioms CumulativeAccessibility.RecursiveAccessibility.emergence_alone_does_not_force_retained_integration

#print axioms CumulativeAccessibility.RecursiveAccessibility.retained_intermediate_creates_second_round_access
#print axioms CumulativeAccessibility.RecursiveAccessibility.depth_expansion_without_search_operator_expansion
#print axioms CumulativeAccessibility.RecursiveAccessibility.search_operator_expansion_without_realized_candidate_step
#print axioms CumulativeAccessibility.RecursiveAccessibility.generatedFromAvailable_unaryLift_iff
#print axioms CumulativeAccessibility.RecursiveAccessibility.generatedFromAvailable_binaryLift_iff
#print axioms CumulativeAccessibility.RecursiveAccessibility.joint_witness_has_generative_arity_two
#print axioms CumulativeAccessibility.RecursiveAccessibility.new_parent_set_implies_evolvabilityLt
#print axioms CumulativeAccessibility.RecursiveAccessibility.retained_module_diversity_expands_generator
#print axioms CumulativeAccessibility.RecursiveAccessibility.retained_module_diversity_derives_secondOrderClick
#print axioms CumulativeAccessibility.RecursiveAccessibility.retained_module_diversity_creates_new_candidate
#print axioms CumulativeAccessibility.RecursiveAccessibility.new_rule_event_implies_GeneratorRuleLt
#print axioms CumulativeAccessibility.RecursiveAccessibility.fixed_repertoire_rule_expansion

#print axioms CumulativeAccessibility.RecursiveAccessibility.strictExpansionCount_le_remaining_capacity
#print axioms CumulativeAccessibility.RecursiveAccessibility.finite_retained_process_saturates
#print axioms CumulativeAccessibility.RecursiveAccessibility.openEndedNovelty_implies_unboundedEnvelopeCapacity
#print axioms CumulativeAccessibility.RecursiveAccessibility.unboundedCapacity_without_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.generativeCapacityUptake_implies_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringSlack_and_realization_imply_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.openEndedNovelty_without_recurringSlack
#print axioms CumulativeAccessibility.RecursiveAccessibility.validatedGenerativeCapacityUptake_implies_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.openEndedNovelty_without_externalValidation

#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringValidatedResponse_implies_recurringOpportunity
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringValidatedResponse_implies_validatedUptake
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_validatedRealization_imply_recurringValidatedResponse
#print axioms CumulativeAccessibility.RecursiveAccessibility.persistentSupport_and_connection_imply_recurringOpportunity
#print axioms CumulativeAccessibility.RecursiveAccessibility.cycle3MaintenanceSupport_persistent
#print axioms CumulativeAccessibility.RecursiveAccessibility.supportedCycle3Maintenance_supplies_recurringOpportunity
#print axioms CumulativeAccessibility.RecursiveAccessibility.supportedCycle3Maintenance_and_validatedResponse_imply_recurringValidatedResponse
#print axioms CumulativeAccessibility.RecursiveAccessibility.supportedCycle3Maintenance_and_validatedResponse_imply_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.supportedCycle3Maintenance_and_validatedResponse_imply_unboundedEnvelope
#print axioms CumulativeAccessibility.RecursiveAccessibility.cycle3Maintenance_supplies_recurringOpportunity
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_alone_does_not_imply_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringValidatedResponse_without_successAtEveryOpportunity
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_uptake_without_recurringCoincidence

#print axioms CumulativeAccessibility.RecursiveAccessibility.resourceValidatedSuccessAt_implies_validatedSuccessAt
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringValidatedResponseWithin_zero_iff
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringValidatedResponseWithin_mono
#print axioms CumulativeAccessibility.RecursiveAccessibility.opportunityConditionedResourceResponseWithin_mono
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringValidatedResponse_implies_within
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringValidatedResponseWithin_implies_validatedUptake
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_resourceResponseWithin_imply_recurringResponseWithin
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_resourceResponseWithin_imply_validatedUptake
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_resourceResponseWithin_imply_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_resourceResponseWithin_imply_unboundedEnvelope

#print axioms CumulativeAccessibility.RecursiveAccessibility.evenOpportunity_has_unitDelayedResourceResponse
#print axioms CumulativeAccessibility.RecursiveAccessibility.evenOpportunity_has_recurring_unitDelayedResponse
#print axioms CumulativeAccessibility.RecursiveAccessibility.unitDelayedResponse_without_sameTimeCoincidence
#print axioms CumulativeAccessibility.RecursiveAccessibility.unitDelayedResponse_without_zeroDelay
#print axioms CumulativeAccessibility.RecursiveAccessibility.validatedSuccess_without_declaredResourceFeasibility
#print axioms CumulativeAccessibility.RecursiveAccessibility.resourceFeasibility_without_validatedSuccess

#print axioms CumulativeAccessibility.RecursiveAccessibility.internallyViableAt_iff_internalSlack_nonneg
#print axioms CumulativeAccessibility.RecursiveAccessibility.endogenousResponseBudget_nonneg
#print axioms CumulativeAccessibility.RecursiveAccessibility.organization_improvement_increases_internalSlack
#print axioms CumulativeAccessibility.RecursiveAccessibility.organization_improvement_increases_endogenousResponseBudget
#print axioms CumulativeAccessibility.RecursiveAccessibility.resourceFeasibleAt_mono_budget
#print axioms CumulativeAccessibility.RecursiveAccessibility.responseBudget_increase_opens_cost_window
#print axioms CumulativeAccessibility.RecursiveAccessibility.resourceFeasibility_switches_across_budget_window
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_endogenousResponseWithin_imply_validatedUptake
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_endogenousResponseWithin_imply_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_endogenousResponseWithin_imply_unboundedEnvelope
#print axioms CumulativeAccessibility.RecursiveAccessibility.margin_increase_opens_response_cost_window

#print axioms CumulativeAccessibility.RecursiveAccessibility.gradient_uptake_improvement_opens_response_feasibility
#print axioms CumulativeAccessibility.RecursiveAccessibility.evenOpportunity_has_endogenouslyFunded_unitDelayedResponse
#print axioms CumulativeAccessibility.RecursiveAccessibility.fixedGradient_endogenousBudget_implies_validatedUptake
#print axioms CumulativeAccessibility.RecursiveAccessibility.fixedGradient_endogenousBudget_implies_openEndedNovelty
#print axioms CumulativeAccessibility.RecursiveAccessibility.exact_first_click_opens_marginFunded_response_feasibility
#print axioms CumulativeAccessibility.RecursiveAccessibility.exact_response_window_matches_second_click_window

#print axioms CumulativeAccessibility.RecursiveAccessibility.dynamicVortexTurn_opens_budget_and_futureSearch
#print axioms CumulativeAccessibility.RecursiveAccessibility.endogenousVortexResponseWithin_implies_endogenousResponseWithin
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_endogenousVortexResponse_imply_recurringSecondOrderUpdate
#print axioms CumulativeAccessibility.RecursiveAccessibility.recurringOpportunity_and_endogenousVortexResponse_imply_fullDynamicConsequences
#print axioms CumulativeAccessibility.RecursiveAccessibility.vortex_baseline_to_one_is_dynamicTurn
#print axioms CumulativeAccessibility.RecursiveAccessibility.vortex_has_integrated_zeroLag_response
#print axioms CumulativeAccessibility.RecursiveAccessibility.vortex_full_dynamic_witness

#print axioms CumulativeAccessibility.RecursiveAccessibility.CostGeometryChangesOn
#print axioms CumulativeAccessibility.RecursiveAccessibility.HasCheaperFutureOn
#print axioms CumulativeAccessibility.RecursiveAccessibility.hasCheaperFutureOn_opens_target_at_some_budget
#print axioms CumulativeAccessibility.RecursiveAccessibility.quantitativeSecondOrderOpening_has_new_target_at_some_budget
#print axioms CumulativeAccessibility.RecursiveAccessibility.quantitativeSecondOrderClick_implies_opening
#print axioms CumulativeAccessibility.RecursiveAccessibility.quantitativeSecondOrderOpening_implies_change
#print axioms CumulativeAccessibility.RecursiveAccessibility.viscosityTradeoff_has_cheaper_future
#print axioms CumulativeAccessibility.RecursiveAccessibility.viscosityTradeoff_not_noMoreViscous
#print axioms CumulativeAccessibility.RecursiveAccessibility.viscosityTradeoff_quantitative_opening
#print axioms CumulativeAccessibility.RecursiveAccessibility.viscosityTradeoff_not_binary_click_at_budget_one

#print axioms CumulativeAccessibility.RecursiveAccessibility.noMoreViscousOn_refl
#print axioms CumulativeAccessibility.RecursiveAccessibility.noMoreViscousOn_trans
#print axioms CumulativeAccessibility.RecursiveAccessibility.strictlyLessViscousOn_trans_noMoreViscousOn
#print axioms CumulativeAccessibility.RecursiveAccessibility.noMoreViscousOn_trans_strictlyLessViscousOn
#print axioms CumulativeAccessibility.RecursiveAccessibility.strictlyLessViscousOn_trans
#print axioms CumulativeAccessibility.RecursiveAccessibility.noMoreViscousOn_preserves_budget_access
#print axioms CumulativeAccessibility.RecursiveAccessibility.strictlyLessViscousOn_opens_budget_window
#print axioms CumulativeAccessibility.RecursiveAccessibility.strictlyLessViscousOn_induces_strictExpansionAtBudget
#print axioms CumulativeAccessibility.RecursiveAccessibility.quantitativeSecondOrderClick_implies_secondOrderClick_at_some_budget
#print axioms CumulativeAccessibility.RecursiveAccessibility.quantitativeSecondOrderClick_has_cheaper_future
#print axioms CumulativeAccessibility.RecursiveAccessibility.viscosityToy_quantitative_click
#print axioms CumulativeAccessibility.RecursiveAccessibility.viscosityToy_binary_click_at_budget_one

#print axioms CumulativeAccessibility.IntelligentLearning.processImprovement_has_cheaper_future
#print axioms CumulativeAccessibility.IntelligentLearning.verbImprovement_opens_budget_window
#print axioms CumulativeAccessibility.IntelligentLearning.selfImprovement_has_cheaper_future
#print axioms CumulativeAccessibility.IntelligentLearning.recursiveSelfImprovement_implies_selfImprovement
#print axioms CumulativeAccessibility.IntelligentLearning.recursiveSelfImprovement_increases_productivity
#print axioms CumulativeAccessibility.IntelligentLearning.rateGroundedRecursiveSelfImprovement_preserves_retained_functions
#print axioms CumulativeAccessibility.IntelligentLearning.rateGroundedRecursiveSelfImprovement_has_faster_learning_target

#print axioms CumulativeAccessibility.FunctionalOrganization.noMoreFunctionallyViscous_iff_nonnegativeVelocity
#print axioms CumulativeAccessibility.FunctionalOrganization.strictlyLessFunctionallyViscous_iff_positiveVelocity
#print axioms CumulativeAccessibility.FunctionalOrganization.strictlyLessFunctionallyViscous_induces_repertoire_expansion
#print axioms CumulativeAccessibility.FunctionalOrganization.positiveFunctionalVelocity_induces_repertoire_expansion
#print axioms CumulativeAccessibility.FunctionalOrganization.positiveFunctionalVelocity_implies_positiveRate
#print axioms CumulativeAccessibility.FunctionalOrganization.strictlyFasterFunctionalRate_has_target
#print axioms CumulativeAccessibility.FunctionalOrganization.acceleratingFunctionalRatchet_has_faster_target
#print axioms CumulativeAccessibility.FunctionalOrganization.commons_positive_functional_velocity
#print axioms CumulativeAccessibility.FunctionalOrganization.commons_repertoire_expands_at_budget_one

#print axioms CumulativeAccessibility.FunctionalOrganization.mechanisticRatchetVelocity_nonneg
#print axioms CumulativeAccessibility.FunctionalOrganization.mechanisticRatchetVelocity_mono_opportunity
#print axioms CumulativeAccessibility.FunctionalOrganization.mechanisticRatchetVelocity_mono_generation
#print axioms CumulativeAccessibility.FunctionalOrganization.mechanisticRatchetVelocity_mono_resource
#print axioms CumulativeAccessibility.FunctionalOrganization.mechanisticRatchetVelocity_mono_validation
#print axioms CumulativeAccessibility.FunctionalOrganization.mechanisticRatchetVelocity_mono_retention
#print axioms CumulativeAccessibility.FunctionalOrganization.mechanisticRatchetVelocity_mono_meanGain
#print axioms CumulativeAccessibility.FunctionalOrganization.matchedLedger_zero_retention_implies_zero_measuredRate

#print axioms CumulativeAccessibility.RecursiveAccessibility.opportunityGapBound_implies_recurringOpportunity
#print axioms CumulativeAccessibility.RecursiveAccessibility.boundedOpportunity_and_response_imply_successGapBound
#print axioms CumulativeAccessibility.RecursiveAccessibility.boundedOpportunity_and_response_imply_successEveryWindow
#print axioms CumulativeAccessibility.RecursiveAccessibility.successGapBound_implies_validatedUptake
#print axioms CumulativeAccessibility.RecursiveAccessibility.persistentSupport_and_connection_imply_zeroGapOpportunity
#print axioms CumulativeAccessibility.RecursiveAccessibility.supportedCycle3Maintenance_supplies_zeroGapOpportunity
#print axioms CumulativeAccessibility.RecursiveAccessibility.supportedCycle3Maintenance_and_boundedResponse_imply_successEveryWindow
#print axioms CumulativeAccessibility.FunctionalOrganization.boundedMechanism_implies_functionalGainEveryWindow
#print axioms CumulativeAccessibility.FunctionalOrganization.supportedCycle3Maintenance_boundedResponse_and_minGain_imply_functionalGainEveryWindow
#print axioms CumulativeAccessibility.FunctionalOrganization.functionalGainEveryWindow_implies_everyBlock
#print axioms CumulativeAccessibility.FunctionalOrganization.functionalGainEveryWindow_and_nonnegative_imply_blockGainLowerBound
#print axioms CumulativeAccessibility.FunctionalOrganization.certifiedBlockGainRate_le_blockAverageFunctionalRate
#print axioms CumulativeAccessibility.FunctionalOrganization.trajectoryRatchetSteps_imply_target_nonnegative
#print axioms CumulativeAccessibility.FunctionalOrganization.boundedMechanism_implies_blockAverageRateFloor
#print axioms CumulativeAccessibility.FunctionalOrganization.supportedCycle3Maintenance_implies_blockAverageRateFloor
#print axioms CumulativeAccessibility.FunctionalOrganization.largerMinimumGain_strictlyRaises_rateFloor
#print axioms CumulativeAccessibility.FunctionalOrganization.shorterResponseLag_strictlyRaises_rateFloor
#print axioms CumulativeAccessibility.FunctionalOrganization.shorterOpportunityGap_strictlyRaises_rateFloor

#print axioms CumulativeAccessibility.FunctionalOrganization.searchValidationVelocity_nonneg
#print axioms CumulativeAccessibility.FunctionalOrganization.searchValidationVelocity_le_quarter
#print axioms CumulativeAccessibility.FunctionalOrganization.searchValidationVelocity_eq_quarter_iff
#print axioms CumulativeAccessibility.FunctionalOrganization.searchValidationVelocity_strictMono_left
#print axioms CumulativeAccessibility.FunctionalOrganization.searchValidationVelocity_strictAnti_right
#print axioms CumulativeAccessibility.FunctionalOrganization.more_search_can_reduce_velocity

#print axioms CumulativeAccessibility.FunctionalOrganization.validationBaselineVelocity_le_stateDependentMaximum
#print axioms CumulativeAccessibility.FunctionalOrganization.validationBaselineVelocity_at_stateDependentOptimum
#print axioms CumulativeAccessibility.FunctionalOrganization.more_validation_baseline_shifts_optimum_toward_search
#print axioms CumulativeAccessibility.FunctionalOrganization.inherited_organization_changes_optimal_allocation
#print axioms CumulativeAccessibility.FunctionalOrganization.symmetric_and_inherited_validation_optima_differ

#print axioms CumulativeAccessibility.FunctionalOrganization.twoBaselineAllocationScore_le_balancedUpperBound
#print axioms CumulativeAccessibility.FunctionalOrganization.twoBaselineAllocationScore_at_balancingAllocation
#print axioms CumulativeAccessibility.FunctionalOrganization.balancingAllocation_equalizes_final_capacities
#print axioms CumulativeAccessibility.FunctionalOrganization.searchFarAhead_all_to_validation_is_optimal
#print axioms CumulativeAccessibility.FunctionalOrganization.validationFarAhead_all_to_search_is_optimal
#print axioms CumulativeAccessibility.FunctionalOrganization.inherited_capacity_moves_the_bottleneck

#print axioms CumulativeAccessibility.FunctionalOrganization.balancingRatePolicy_optimalAt_interior
#print axioms CumulativeAccessibility.FunctionalOrganization.twoBaselineAllocationScore_eq_upperBound_iff_balancing
#print axioms CumulativeAccessibility.FunctionalOrganization.optimalActionAt_interior_eq_balancing
#print axioms CumulativeAccessibility.FunctionalOrganization.allocation_preference_reverses_across_states
#print axioms CumulativeAccessibility.FunctionalOrganization.no_fixed_allocation_optimal_at_both_witness_states
#print axioms CumulativeAccessibility.FunctionalOrganization.adaptive_policy_succeeds_where_fixed_action_cannot

#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckRatePolicy_feasible
#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckRatePolicy_eq_balancing_of_interior
#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckRatePolicy_optimalAt
#print axioms CumulativeAccessibility.FunctionalOrganization.global_adaptive_policy_succeeds_where_fixed_action_cannot

#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckClosedLoopStep_adds_one_total_capacity
#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckClosedLoop_imbalance_law
#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckClosedLoop_preserves_balance
#print axioms CumulativeAccessibility.FunctionalOrganization.interior_step_makes_next_policy_half
#print axioms CumulativeAccessibility.FunctionalOrganization.closedLoop_policy_is_recursive_on_interior_state

#print axioms CumulativeAccessibility.FunctionalOrganization.scalarOptimal_implies_unitLift_paretoUndominated
#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckRatePolicy_unitLift_paretoUndominated
#print axioms CumulativeAccessibility.FunctionalOrganization.strictlyFasterActionOn_not_reverse
#print axioms CumulativeAccessibility.FunctionalOrganization.strictFunctionalPolicyImprovement_has_witness

#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckPolicy_dominates_fixedHalf_on_witnessStates
#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckPolicy_strictlyImproves_fixedHalf_on_witnessStates
#print axioms CumulativeAccessibility.FunctionalOrganization.fixedHalfPolicy_not_optimal_at_validationRich_state
#print axioms CumulativeAccessibility.FunctionalOrganization.learned_state_sensitivity_can_improve_policy

#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckPolicy_action_adapts_without_policy_rule_change
#print axioms CumulativeAccessibility.FunctionalOrganization.fixedHalf_and_bottleneck_agree_at_symmetric
#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckPolicy_preserves_fixedHalf_on_retained_state
#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckPolicy_strictlyImproves_fixedHalf_on_heldOut_state
#print axioms CumulativeAccessibility.FunctionalOrganization.bottleneckPolicy_is_heldOut_learning_improvement
#print axioms CumulativeAccessibility.FunctionalOrganization.endogenousPolicyLearning_implies_heldOutImprovement
#print axioms CumulativeAccessibility.FunctionalOrganization.endogenous_bottleneckPolicy_learning_of_generated_update

#print axioms CumulativeAccessibility.FunctionalOrganization.allocationRateRegret_eq_residualImbalance_sq_div_four
#print axioms CumulativeAccessibility.FunctionalOrganization.allocationRateRegret_nonnegative
#print axioms CumulativeAccessibility.FunctionalOrganization.fixedHalf_rateRegret_eq_baselineImbalance_sq_div_four
#print axioms CumulativeAccessibility.FunctionalOrganization.balancing_gain_over_fixedHalf_eq_baselineImbalance_sq_div_four
#print axioms CumulativeAccessibility.FunctionalOrganization.validationRich_bottleneckPolicy_gain_over_fixedHalf_is_one_sixteenth
#print axioms CumulativeAccessibility.FunctionalOrganization.twoStateMeanFixedRegret_decomposition
#print axioms CumulativeAccessibility.FunctionalOrganization.twoStateMeanFixedRegret_lowerBound
#print axioms CumulativeAccessibility.FunctionalOrganization.bestTwoStateFixedAllocation_attains_heterogeneityFloor
#print axioms CumulativeAccessibility.FunctionalOrganization.witnessStates_stateSensitivity_eliminates_fixedPolicy_floor
#print axioms CumulativeAccessibility.FunctionalOrganization.certifiedBlockGainRate_positive

#print axioms CumulativeAccessibility.RecursiveAccessibility.concreteMaintenanceToValidatedNoveltyWitness
#print axioms CumulativeAccessibility.RecursiveAccessibility.concreteMaintenanceToValidatedNoveltyWitness_unbounded
#print axioms CumulativeAccessibility.RecursiveAccessibility.concreteMaintenanceGatedNoveltyWitness
#print axioms CumulativeAccessibility.RecursiveAccessibility.noOpportunity_gatedArchitecture_not_openEnded
