name: Build Docs

# 1) Allow the GITHUB_TOKEN to push changes back
permissions:
  contents: write

# 2) Trigger on every push to main
on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # 3) Checkout your repo on the 'main' branch and keep the token
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main                   # explicitly check out main
          persist-credentials: true   # keep GITHUB_TOKEN for pushes
          fetch-depth: 0              # fetch full history

      # 4) Install pandoc for conversion
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      # 5) Convert every .tex (except main.tex) into Markdown under docs/
      - name: Convert LaTeX files to Markdown
        shell: bash
        run: |
          set -euxo pipefail

          # Find all .tex except your root and any CI files
          find . \
            -type f \
            -name '*.tex' \
            ! -name 'main.tex' \
            ! -path './.github/*' \
            ! -path './.git/*' \
            -print | while read -r tex; do

            # Compute relative path and output path
            rel="${tex#./}"
            out="docs/${rel%.tex}.md"

            echo "Converting $rel → ${out#docs/}"
            mkdir -p "$(dirname "$out")"
            pandoc "$tex" \
              --from=latex --to=gfm \
              --standalone \
              --mathjax \
              -o "$out"
          done

      # 6) Commit & push the generated docs back to main
      - name: Commit and push generated docs
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Make sure we're on main
          git checkout -B main

          # Pull/rebase any remote commits
          git pull --rebase origin main

          # Stage the entire docs/ folder
          git add docs/

          # Only commit if there are staged changes
          git diff --cached --quiet || git commit -m "Rebuild docs from LaTeX"

          # Push your new docs back up
          git push origin main
