name: Build Docs

# 1) Grant the GITHUB_TOKEN write permissions on repo contents
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  tex2md:
    runs-on: ubuntu-latest

    steps:
      # 2) Checkout and persist the token so we can push back
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # <-- important!
          fetch-depth: 0

      # 3) Install pandoc
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      # 4) Convert LaTeX → Markdown
      - name: Convert all LaTeX to Markdown
        run: |
          mkdir -p docs/Frontmatter docs/Chapters docs/Backmatter
          for dir in Frontmatter Chapters Backmatter; do
            for tex in $dir/*.tex; do
              md="docs/$dir/$(basename "${tex%.tex}.md")"
              pandoc "$tex" \
                --from=latex --to=gfm --standalone --mathjax \
                -o "$md"
            done
          done

      # 5) Commit & push generated docs
      - name: Commit and push generated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --quiet || git commit -m "Rebuild docs from LaTeX"
          git push
