permissions:
  contents: write

on: [push]

jobs:
  tex2md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert all LaTeX to Markdown
        run: |
          set -euxo pipefail
          mkdir -p docs/Frontmatter docs/Chapters docs/Backmatter
          shopt -s nullglob
          for dir in Frontmatter Chapters Backmatter; do
            for tex in "$dir"/*.tex; do
              out="docs/$dir/$(basename "${tex%.tex}.md")"
              pandoc "$tex" --from=latex --to=gfm --standalone --mathjax -o "$out"
            done
          done

      - name: Commit and push generated docs
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add docs/
          git diff --quiet || git commit -m "Rebuild docs from LaTeX"
          git push origin main
