name: Build Docs

on:
  push:
    branches: [ main ]

jobs:
  tex2md:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Convert LaTeX chapters to Markdown
      run: |
        mkdir -p docs
        for tex in chapters/chapter*.tex; do
          md="docs/$(basename "${tex%.tex}.md")"
          pandoc "$tex" \
            --from=latex \
            --to=gfm \
            --standalone \
            --mathjax \
            -o "$md"
        done

    - name: Commit and push generated docs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/
        git diff --quiet || git commit -m "Rebuild docs from LaTeX" 
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
