# GitHub Pages build & deploy — LaTeX ➜ Markdown *with* Lua‑front‑matter
# ===================================================================
# • Trigger: push to main
# • Reads version from last Git tag → $BOOK_VERSION
# • Converts every src/chapters/*.tex (excl. main.tex) to docs/Chapters/*.md
#   using filters/add_yaml.lua to inject YAML front‑matter (id, title, version…)
# • Builds MkDocs site and deploys to GitHub Pages

name: Build & Deploy Site

permissions:
  contents: write
  pages:    write
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      # --- Checkout ----------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # we need tags for version extraction

      # --- Toolchain ---------------------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pandoc & MkDocs‑Material
        run: |
          sudo apt-get update && sudo apt-get install -y pandoc
          pip install mkdocs-material

      # --- TikZ ➜ PDF ➜ SVG -----------------------------------------
      - name: Setup Tectonic (LaTeX engine)
        uses: WtfJoke/setup-tectonic@v3          # één binary, geen TeX Live

      - name: Render standalone TikZ files to PDF & SVG
        run: |
          sudo apt-get install -y pdf2svg        # piepklein CLI
          # Zoek alle docs/figures/*.tex bestanden en zet ze om
          for tex in $(find docs/figures -name '*.tex'); do
            base="${tex%.tex}"
            tectonic -Z shell-escape "$tex"      # → layers.pdf
            pdf2svg "${base}.pdf" "${base}.svg"  # → layers.svg
          done

      # (optioneel) commit nieuwe/gewijzigde figuren terug
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/figures/*.pdf docs/figures/*.svg'
          message: 'ci: auto‑update figures'

      # --- Version info ------------------------------------------------
      - name: Compute version from last tag
        run: |
          echo "BOOK_VERSION=$(git describe --tags --abbrev=0 || echo 0.0-dev)" >> $GITHUB_ENV
          echo "Version for build: $BOOK_VERSION"

      # --- LaTeX ➜ Markdown (Lua filter) -------------------------------
      - name: Convert LaTeX to Markdown with YAML front‑matter
        shell: bash
        run: |
          set -euxo pipefail
          # Vind álle .tex (behalve main.tex) in de hele repo
          while IFS= read -r -d '' tex; do
            # strip leading "./"
            rel="${tex#./}"
            # output path onder docs/
            out="docs/${rel%.tex}.md"
            mkdir -p "$(dirname "$out")"
            pandoc "$tex" \
              --from=latex --to=markdown+fenced_divs \
              --standalone --mathjax --wrap=none \
              --lua-filter=filters/pdf2svg.lua \
              --lua-filter=filters/add_yaml.lua \
              -o "$out"
          done < <(
            find . \
              -type f -name '*.tex' \
              ! -name 'main.tex' \
              ! -path './docs/figures/*' \
              ! -path './.github/*' \
              ! -path './.git/*' \
              -print0
          )

      # --- MkDocs build ----------------------------------------------
      - name: Build site
        run: mkdocs build --strict

      # --- GitHub Pages publish --------------------------------------
      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
