name: Build & Deploy Site

permissions:
  contents: read
  pages:    write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    # ← Add this to specify the Pages environment
    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y pandoc
          pip install mkdocs-material

      - name: Convert LaTeX to Markdown
        shell: bash
        run: |
          set -euxo pipefail
          find . \
            -type f \
            -name '*.tex' \
            ! -name 'main.tex' \
            ! -path './.github/*' \
            ! -path './.git/*' \
            -print | while read -r tex; do
            rel="${tex#./}"
            out="docs/${rel%.tex}.md"
            mkdir -p "$(dirname "$out")"
            pandoc "$tex" \
              --from=latex \
              --to=gfm \
              --standalone \
              --mathjax \
              -o "$out"
          done

      - name: Build site
        run: mkdocs build --strict

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
