name: Deploy MkDocs site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install MkDocs and the Material theme
      - name: Install MkDocs
        run: pip install mkdocs-material

      # 4) Build the site (reads from docs/, writes to site/)
      - name: Build MkDocs site
        run: mkdocs build

      # 5) Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
